### ISSUE TITLE
force auto reconnect to debian host after user logoit

### ISSUE THREAD

**Issue by pcs3rd** [rdesktop/rdesktop#102]
I am using a pi. It needs to be so that if someone logs out, instead of giving desktop access, it takes them back to the xrdp logging screen after reconnecting.

**Comment by hean01-cendio** [comment]
I do not see why we should add this to rdesktop when it is easily done using a wrapper shell script for rdesktop, something like:

```
#!/bin/sh
while /bin/true; do
    rdesktop -f $1
done
```

and use like:

```
$ ./wrapper.sh myserver.local.tld
```
