### ISSUE TITLE
Newest rdesktop not working with barracuda VPN

### ISSUE THREAD

**Issue by lukeallister** [rdesktop/rdesktop#108]
My company uses a Barracuda VPN for remote logins. When I tried to access this from a linux box running the latest version (1.8.3) it merely created a connection and closed the connection--rdesktop couldn't connect. 

I installed the latest known working version from source (1.7.1) and it works perfectly. I do not know where to find more detail, but somehow there is a problem introduced with the latest version. 

Any ideas?

**Comment by hean01-cendio** [comment]
@lukeallister is it possible for you to build rdesktop from source and run:

  $ RDESKTOP_DEBUG=All rdesktop <server>

and then post the output for the comand ?

**Comment by lukeallister** [comment]
Unfortunately I can't initiate a connection from the client side. There is a proprietary java launcher that shepherds users through a 2-factor login and then launches rdesktop via a graphical button. That's why I'm having a difficult time figuring out more detail.

**Comment by hean01-cendio** [comment]
Then its pretty hard for us to help you out on this issue. Maybe contact the authors of the proprietary java launcher for assistance ? At least get information how to obtain the output of execution of the rdesktop process for inspection.

**Comment by jhudsoncedaron** [comment]
If you can install a version from source you can place a script where rdesktop normally goes that calls the real rdesktop with an arbitrary environment.

**Comment by lukeallister** [comment]
That sounds like it might be possible. If rdesktop lives at `/usr/local/bin/rdesktop` then do you mean moving it somewhere else and creating a bash script that I call "rdesktop" that calls the new location with the debug command? I'm not sure how the java launcher calls rdesktop in the first place or how I would pass the server or the commands to the real version . . . . 

Am I on the right track?

Thanks for your help

**Comment by hean01-cendio** [comment]
Here follows a simple wrapper script which will left a /tmp/rdesktop.log file behind. Find and rename rdesktop binary to rdesktop.bin and create the wrapper script with the content below, named rdesktop in place of the orginal file. Make sure the script has the executable flag set.

```
#!/bin/sh
pushd /tmp
RDESKTOP_DEBUG=All rdesktop.bin $@ > rdesktop.log 2>&1
popd
```
To revert the change, just move rdesktop.bin to rdesktop.

**Comment by lukeallister** [comment]
I had to tweak the script just a bit because it didn't have correct permissions to write the log file to a /bin directory. While I was at it, I added a line to log exactly what commands it passes:
`#!/bin/bash
pushd /tmp
echo $@ >> /home/luke/Downloads/rdesktop.log 
RDESKTOP_DEBUG=ALL rdesktop.bin $@ >> /home/luke/Downloads/rdesktop.log 2>&1
popd`

When I run this with rdesktop 1.7.1 I simply get: 
`-f -z -a 16 -r clipboard:CLIPBOARD 127.0.0.1:37906
Autoselected keyboard map en-us`

I then installed the debian package for 1.8.3 from https://packages.debian.org/sid/amd64/rdesktop/download and got this message:
`-f -z -a 16 -r clipboard:CLIPBOARD 127.0.0.1:39595
Autoselected keyboard map en-us
ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?
ERROR: 127.0.0.1: unable to connect`

I'm excited to see an error message, but unfortunately don't know anything about CredSSP. 

Any thoughts?

**Comment by jhudsoncedaron** [comment]
That's the same error I get referenced at https://github.com/rdesktop/rdesktop/issues/101#issuecomment-290307166 maybe it's the same bug.

**Comment by hean01-cendio** [comment]
@lukeallister , ignore the credssp error (its just a warning actually). I rewrote the logging of rdesktop which is available in source, could you build rdesktop from source to get better logging ?

@jhudsoncedaron , are you sure ?, because the error ("ERROR: 127.0.0.1: unable to connect") is raised when connect() call fails.

**Comment by joshudson** [comment]
Wow! I wonder what strange thing MS did.

**Comment by joshudson** [comment]
Turned out the line I was keying off of was the garbage line about CredSSP not finding kerberosis. It's pretty useless; it happens whenever the target OS supports kerberosis but the host OS doesn't. It's really curious he got the connection failed after the CredSSP line. I'm pretty sure that connect() has to succeed to know what the target supports.

**Comment by hean01-cendio** [comment]
@joshudson you are a bit misinformed, CredSSP fails at initialize, eg there are no tgt in the kerberos cache, this is a local check and does not require a connect() to be carried out. rdesktop uses a fallback chain -> CredSSP(kerberos) -> TLS -> Plain RDP, i any of the stages fails, next in chain is tried.

**Comment by lukeallister** [comment]
@hean01-cendio I am traveling and won't have a chance to test a new build from source for about a week. I'll test it as soon as I get a chance and let you know.

**Comment by hean01-cendio** [comment]
@lukeallister did you find the cause to this problem ? If its not a problem anymore eg. related to rdesktop, please do close this issue.

**Comment by lukeallister** [comment]
Sorry, I keep forgetting to check. For now I am fine using the previous release, so unless other users have a problem I'll close the issue and live with it.
