### ISSUE TITLE
There is no ./configure script

### ISSUE THREAD

**Issue by douglasheld** [rdesktop/rdesktop#11]
I would like to build on Apple OS X and there is no configure script as documented in the README.

**Comment by hean01-cendio** [comment]
The information how to build snapshot of the source is available in the README. However it was not reflecting the move to GitHub.

README is updated in commit d529a86

**Comment by douglasheld** [comment]
Thank you!
Success steps:
sudo yum install autoconf libgssglue-devel automake libX11-devel openssl-devel
./bootstrap
./configure --disable-smartcard
make
sudo make install
