### ISSUE TITLE
Mouse lost control

### ISSUE THREAD

**Issue by uzazzap** [rdesktop/rdesktop#111]
Hi!
User connecting to windows 2008 r2 terminal with rdesktop versions 1.7.0 and 1.8.3, and at random time mouse lost control, that is cursor still moving but button pressing ignored. Keyboard same time working and let call task manager etc. This problem taked on xubuntu 12.04.05 LTS (rdesktop ver 1.7.0) and Ubuntu 14.04.5 LTS (rdesktop ver 1.8.3). 
How can I fix it, or help for fix?

**Comment by Stewie313** [comment]
Good afternoon! Did you manage to solve this problem?
