### ISSUE TITLE
pkg-config not detected properly

### ISSUE THREAD

**Issue by The-Compiler** [rdesktop/rdesktop#112]
On Archlinux, with autoconf 2.69 and pkg-config 0.29.1, when trying to build from git, `pkg-config` is detected according to `config.log`:

```
configure:4671: checking for pkg-config
configure:4689: found /usr/bin/pkg-config
configure:4701: result: /usr/bin/pkg-config
```

but then not used:

```
configure:5135: WARNING: pkg-config not available, cannot check for libgssglue
```

[full config.log](http://paste.the-compiler.org/view/970289f5)

**Comment by hean01-cendio** [comment]
Here follows the source snippet in configure.ac which causes the problem:

```
dnl Don't depend on pkg-config
m4_ifdef([PKG_CHECK_MODULES], [], [
                m4_errprint([warning: pkg-config checks are not available])
                m4_defun([PKG_CHECK_MODULES], [
                        AC_MSG_WARN([pkg-config not available, cannot check for $2])
                        $4
                ])
])
```
added with commit:

```
commit a520715f009389710393fbc92f7656fb662ebe69
Author: Michael Gernoth <michael@gernoth.net>
Date:   Wed Nov 15 09:15:36 2006 +0000

    Don't depend on pkg-config during bootstrap
    
    
    git-svn-id: svn://svn.code.sf.net/p/rdesktop/code/trunk/rdesktop@1334 423420c4-83ab-492f-b58f-81f9feb106b5
```
With that in mind, I think we just should remove the code from configure.ac. I have never seen such fencing before, I can't come up with any reasoning behind it and obviously ir dosn't work reliable.

@The-Compiler could you just rip that code out of configure.ac and rebuild to see if that solves your issue. Be sure to verify that PKG_CHECK_MODULES actually works.

**Comment by The-Compiler** [comment]
Looks like it's actually undefined then:

```
./configure: line 5129: syntax error near unexpected token `GSSGLUE,'
./configure: line 5129: `	    PKG_CHECK_MODULES(GSSGLUE, libgssglue, WITH_CREDSSP=1, WITH_CREDSSP=0)'
```

However, running `aclocal` (and not only `autoconf`) makes things work... so this is probably just me using autoconf the wrong way :wink:

Other projects typically have a `autogen.sh` or `bootscript` thing which does everything needed to generate a working `configure`, FWIW.

**Comment by hean01-cendio** [comment]
rdesktop also have a bootstrap script mentioned in README.md :). Did your problem came from running this script or by running autotools by yourself ?

**Comment by The-Compiler** [comment]
Whooops, no idea how I missed that! 😊 All works fine when using that script. Sorry for the noise!
