### ISSUE TITLE
Client screen resize handled incorrectly

### ISSUE THREAD

**Issue by reqolf** [rdesktop/rdesktop#117]
When in fullscreen mode and a size change of local display occurs, the remote screen is changed to fit the new size but client window stays black outside the old boundaries, so that only the upper-left corner of the remote desktop is visible.

It seems that clip area should be reset after resize or generally after a reconnect loop.

I fixed it with the following patch, but I'm not sure it is completely correct:

```
diff -Naurp rdesktop-1.8.3.original/rdesktop.c rdesktop-1.8.3/rdesktop.c
--- rdesktop-1.8.3.original/rdesktop.c  2015-08-21 14:12:27.000000000 +0200
+++ rdesktop-1.8.3/rdesktop.c   2017-05-05 17:47:27.000000000 +0200
@@ -1174,6 +1174,8 @@ main(int argc, char *argv[])
                DEBUG(("Connection successful.\n"));

                rd_create_ui();
+               if (g_reconnect_loop)
+                       ui_reset_clip();
                tcp_run_ui(True);

                deactivated = False;
```

**Comment by hean01-cendio** [comment]
Nice, I will take a look at it.
