### ISSUE TITLE
Archive rdesktop-1.8.3.tar.gz misses en-us-intl keymap

### ISSUE THREAD

**Issue by eraserix** [rdesktop/rdesktop#122]
The archive at https://github.com/rdesktop/rdesktop/releases/download/v1.8.3/rdesktop-1.8.3.tar.gz is missing the en-us-intl keymap. The two variants of "Source code" archives do contain the layout.

**Comment by hean01-cendio** [comment]
Nice find, added a fix for that in commit 	2615f08 for upcoming release.
