### ISSUE TITLE
File copying is not working from Linux to Windows

### ISSUE THREAD

**Issue by efficia** [rdesktop/rdesktop#124]
Hi,
Clipboard is working fire but not able to copy files from Linux to Windows.
Please assist.
Thanks

**Comment by hean01-cendio** [comment]
Clipboard does only support transfer of text. If you want to transfer files between linux and windows session you should use the local drive redirection such as:

    rdesktop <server> -r disk:home=/home/username

This will give you access to a drive within windows session named home which will show you the home directory of "username" on your linux client.
