### ISSUE TITLE
Enable rdekstop debug file

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#126]
Hi,

It seems that rdekstop allow RDESKTOP_DEBUG=All to debug, but I liek to know it it is possible to save debug output to file.
How can we do this?

Thanks

**Comment by uglym8** [comment]
Hi,

Just redirect stderr to a file e.g.:
<code>
RDESKTOP_DEBUG=All ./rdesktop server_ipa 2> /tmp/rdp.debug.log
</code>

Regards.
