### ISSUE TITLE
Connecting to RDS expects that password are available before connect

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#127]
We could solve this with several mechanisms the following two comes to mind:

1. Prompt for password input via stdin if no password is supplied via command line arguments
2. Use an askpass mechanism eg. such as from ssh:
```
SSH_ASKPASS    If ssh needs a passphrase, it will read the passphrase from the 
               current terminal if it was run from a terminal.  If ssh does not
               have a terminal associated with it but DISPLAY and SSH_ASKPASS 
               are set, it will execute the program specified by SSH_ASKPASS 
               and open an X11 window to read the passphrase. This is particularly
               useful when calling ssh from a .xsession or related script.  
               (Note that on some machines it may be necessary to redirect the 
               input from /dev/null to make this work.)
```

**Comment by hean01-cendio** [comment]
This is a potential solution for issue #8 with double login prompts while connecting to session broker and gets redirected.

**Comment by hean01-cendio** [comment]
We should also decide on pull request #116, eg. providing password through environment.

**Comment by hean01-cendio** [comment]
The idea is to check whenever SSH_ASKPASS is available for use, if NOT fallback to internal code that provides a prompt to console and reads the password from stdin.

**Comment by trentasis** [comment]
Anybody can describe how to use, for example an example hot to test with latest master branch... if this is available... 

This can help many people!
Thanks

**Comment by hean01-cendio** [comment]
@trentasis These are ideas and are not yet implemented

**Comment by hean01-cendio** [comment]
Commit 1aaafc80 changes the behavior of rdesktop to always prompt for a password if not provided. This is the first obviously change. SSH_ASKPASS is questionable due to it requires infrastructure for it to work. such ass ssh-gnome-askpass and environment variables.
