### ISSUE TITLE
Migrate from OpenSSL to GnuTLS, Nettle and libtasn1

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#128]
The licensing of OpenSSL is questionable and it is an all in one solution for crypto. It would be very nice to migrate away to components such as GnuTLS, nettle and libtasn1 for a cleaner and more isolated code.

Any thought about this ?

**Comment by uglym8** [comment]
AFAIU, libreSSL has the same dual licence as OpenSSL does (I was gonna suggest it for using).
I was not able to find any *terrible* news regarding GnuTLS so maybe it's really a good choice and worth trying.

**Comment by hean01-cendio** [comment]
GnuTLS branch is now merged into master
