### ISSUE TITLE
Desktop support too?

### ISSUE THREAD

**Issue by ShalokShalom** [rdesktop/rdesktop#132]
Does this work for Windows 7 etc desktop support too?

**Comment by uglym8** [comment]
Could you elaborate a little your question?
Do you want to build and use rdesktop on Windows or do you want to use rdesktop on any supported platfrom (besides Windows) to connect to Windows 7 machine?

**Comment by ShalokShalom** [comment]
The current text suggest, there is only Windows Server support.

**Comment by uglym8** [comment]
The short answer is yes.
The long answer it depends on what you want to achieve:)

Yes, rdesktop supports Windows 7 (btw, XP too) with one caveat:
you either have desktop session (i.e. at your screen on Windows box) or terminal session (i.e. using rdesktop from any supported UNIX-like OS) not 2 discrete simultaneous sessions.

AFAIK there're many variants of desktop Windows OS (e.g. Home. Professional, Ultimate, etc) so maybe some of them supports simultaneous sessions.

**Comment by ShalokShalom** [comment]
Ah ok i see.
