### ISSUE TITLE
Rdesktop 1.9.0

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#133]
Hi,

I think that could be interesting to release a new rdesktop version (1.8.4), latest was 2 years ago

I think that two bugs could be interesting that will be solved in this version
- smartcard https://github.com/rdesktop/rdesktop/issues/109, I think that is sovled but now I'm testing and I hope to inform about the result
- double authentication windows 2012r2, I have checked multiple bugs related wit this issue, but I'm not sure about the possible solution:
https://github.com/rdesktop/rdesktop/issues/127
https://github.com/rdesktop/rdesktop/pull/116
https://github.com/rdesktop/rdesktop/issues/8
If exist a valid solution, I can test in my environment, and I think will be and interesting feature for many users

Thanks and great job!

**Comment by sean729** [comment]
If the capacity to "shadow" an existing RDP session was included in a new rdesktop release, that would be really helpful.

**Comment by uglym8** [comment]
@sean729 Please add an issue regarding "shadowing" as a separate ticket. It'd be easier to track it and
to discuss what has to be done. Thank you.

**Comment by sean729** [comment]
Done, submitted as per your instructions. See https://github.com/rdesktop/rdesktop/issues/141

Thanks for the guidance.

**Comment by rosset** [comment]
time to bump release?

**Comment by opoplawski** [comment]
Would be nice to have the CredSSP fixes out - I'm having to use a locally built package on Fedora now.

**Comment by cemeyer** [comment]
I would also appreciate a released version past the OpenSSL 1.1.x changes that were committed two years ago :-).

**Comment by hean01-cendio** [comment]
Closing this issue, follow status of milestone [1.9.0](https://github.com/rdesktop/rdesktop/milestone/1)

**Comment by trentasis** [comment]
Hi,  checking https://github.com/rdesktop/rdesktop/milestones seems that all issues are solved in 1.9, when will be releasesd 1.9.0?

Thanks

**Comment by CendioOssman** [comment]
Hopefully soon. We've been a bit busy with other things unfortunately. Should be out in a few weeks with some luck.

**Comment by trentasis** [comment]
Thanks!

Missatge de Pierre Ossman (Work account) <notifications@github.com> del dia
dj., 18 d’abr. 2019 a les 10:25:
