### ISSUE TITLE
libvncserver header files in vnc/ are 15 years old?

### ISSUE THREAD

**Issue by timofonic** [rdesktop/rdesktop#134]
The [libvncserver](/LibVNC/libvncserver) project is updated regularly, with commits since some days ago. Unfortunately, it seems the code here is quite old. I'm not sure if old headers still work in newer code, I just notify it and would like to know the status of this code.

I'm very sorry about the possible annoyances caused by this message :D 

- Commits on Jan 14, 2010
   - @astrand: Update the license for uiports/vnc to GPLv3. 

- Commits on Oct 7, 2004
   - @astrand: Indent fixes

**Comment by uglym8** [comment]
AFAIK vnc related stuff is going to be removed.
Check #26, #95

**Comment by hean01-cendio** [comment]
Close due to duplicated of #26 ans specific issue #95
