### ISSUE TITLE
Debian Jessie - connection successful but no background or menus visible

### ISSUE THREAD

**Issue by hgbutte77** [rdesktop/rdesktop#135]
Hello,
I'm trying to establish a rdesktop connection between two Debian8-Jessie workstations. The login procedure seems to be successful (I can't recognize any error). But the only sight I get is a window with a gray background and cross as mouse cursor. 
![rdesktop_screenshot0](https://user-images.githubusercontent.com/28561652/28619794-aaf9b6b4-71f9-11e7-93fe-a3e8e007359d.png)
![rdesktop_screenshot1](https://user-images.githubusercontent.com/28561652/28619804-b35a1a9c-71f9-11e7-970e-085b484890d8.png)
What's going wrong there? How can I debug this issue? I get no relevant message concerning rdesktop?

Many Thanks in advance!
Best regards,
Tobi.

**Comment by hean01-cendio** [comment]
We do not develop / test rdesktop against xrdp and does not know how well it will work. However it seems that the problem you have is not at all related to rdesktop but how a session is started in xrdp / xstartup. You can verify that by reproducing the problem with a mstsc (Windows rdp client)...
