### ISSUE TITLE
pkg-config checks are not available

### ISSUE THREAD

**Issue by omag0** [rdesktop/rdesktop#138]
I lost all day trying to install the rdesktop 1.7.1
When i do autoconf show "warring: pkg-config checks are not available" error. 
If i continue and do ./configure, make, will show the "Makefile:160: recipe for target 'ssl.o' failed
make: *** [ssl.o] Error 1" error."
Anyone can help? 

ps: sorry for the bad english.

**Comment by uglym8** [comment]
Hi,
Try to install pkg-config.
What OS/distro do you use?

**Comment by omag0** [comment]
debian 9. 
I already have pkg-config.

**Comment by uglym8** [comment]
$ cat /etc/debian_version
9.1.
$ dpkg -l pkg-config
ii  pkg-config                  0.29-4+b1             amd64        manage compile and link flags for libraries

$ ./bootstrap && ./configure
...
checking mntent.h usability... yes
checking mntent.h presence... yes
checking for mntent.h... yes
checking for setmntent... yes
configure: creating ./config.status
config.status: creating Makefile

After that depending of whether you installed "libssl-dev" or "libssl1.0-dev" you may encounter failure during ssl.c compilation.

You got two options:
1) Install libssl1.0-dev and build 1.7.1
2) Download latest release (checkout the most recent version) and build it

**Comment by omag0** [comment]
Works!
Thx a lot!

**Comment by uglym8** [comment]
Glad that I could help:)
Could you close this issue, please, then?
