### ISSUE TITLE
No sound on my local system

### ISSUE THREAD

**Issue by alecnaylor** [rdesktop/rdesktop#142]
I am using the rdesktop software to open an RDP session to a Windows 2008 R2 server farm from a raspberry PI running debian but there is not sound coming from the headphones connected to the anologue jack.

I have confirmed that the sound works locally by running a sound test from the raspberry pi console using the following command
-> sudo aplay /usr/share/sounds/alsa/Front_Center.wav

I have checked the rdesktop.config file and tried both sound drivers but neither work
-> -r sound:local:alsa
-> -r sound:local:oss

I have confirmed that both remote desktop session hosts have been configured to redirect audio as I can connect to them from my windows 10 PC and sound comes through my headphones

**Comment by hean01-cendio** [comment]
Do your RPI distribution use pulseaudio or is it plain alsa system ?

What version of rdesktop is used ?

> sudo aplay /usr/share/sounds/alsa/Front_Center.wav

Why do you use sudo ?

**Comment by alecnaylor** [comment]
I used the ALSA sound drivers. I have now managed to get the sound to work by adding the command below to the rdesktop.config file this time but the sound is very choppy.
-r sound:local:alsa

What is the best way to clean up the sound? I can't remember the version of RDesktop that i'm using.

**Comment by hean01-cendio** [comment]
Pull request #152, adds support for pulseaudio, which you could try if you have the know how to build a project from source.

**Comment by hean01-cendio** [comment]
Close due to no response
