### ISSUE TITLE
Increase maximum password length

### ISSUE THREAD

**Issue by pillarsdotnet** [rdesktop/rdesktop#144]
Because certain three-letter agencies have demonstrated an ability to crack 32-character passwords in real-time, my employer has mandated that all passwords be a minimum of 64 randomly-generated characters.  When I set a 64-character password for Windows, I could no longer log in via rdesktop.  Some investigation revealed a hard-coded 63-byte password length limitation, as the character array is declared with length 64, including the null-byte terminator.

Windows supports passwords of up to 256 bytes (128 wide-byte characters), so rdesktop ought to do the same.

It would be better yet to support 256 bytes *by default*, and allow the limit to be increased or decreased via compilation switches.

**Comment by hean01-cendio** [comment]
Maximum length of password field sent in client info PDU is 32 bytes for rdp version <=5.0 and 512 bytes for rdp version 5.1 and later, including mandatory null terminator.

**Comment by pillarsdotnet** [comment]
Abandoning this issue.
