### ISSUE TITLE
rdesktop crash to windows 2003

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#146]
With latest rdesktop, master, using with win2003 in some situations and scrren rdesktop crash. Without fullscrren works and with fullscreen fails.
Same situation with windows 2012 r2 works and with windows 2003 and old rdesktop version, for exaple 1.5 works

Example ouput 

 with /f not working
 rdesktop -f server
Autoselecting keyboard map 'es' from locale
Protocol(warning): Protocol negotation failed with reason: SSL not allowed by server
Retrying with plain RDP.
Sound(error): rdpsnd_process(), Opcode = 0x7 Length= 840
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  56 (X_ChangeGC)
  Value in failed request:  0x74
  Serial number of failed request:  5507
  Current serial number in output stream:  6181

 without /f works
 rdesktop server
Autoselecting keyboard map 'es' from locale
Protocol(warning): Protocol negotation failed with reason: SSL not allowed by server
Retrying with plain RDP.
Sound(error): rdpsnd_process(), Opcode = 0x7 Length= 840

**Comment by uglym8** [comment]
Hi!
Tried to reproduce this issue with W2K3 R2 but couldn't get any crash.

1) How often do these crashes occur?
2) Maybe it fails with some other Windows distributions too?
3) What OS do you run rdesktop on?

TIA.
Best regards.

**Comment by trentasis** [comment]
Hi,

How often do these crashes occur?
--> Always in one situation that is used in windows 2003
Maybe it fails with some other Windows distributions too?
--> NO
What OS do you run rdesktop on?
--> Linux Crux

**Comment by uglym8** [comment]
Ok.
Thank you for updated info (gracias por su información:)).

Could you, please, run rdesktop on the another GNU/Linux distro to make sure that the problem persists?
I'll check the plain 2003 (instead of Win 2003 R2) in the evening.

TIA.

**Comment by uglym8** [comment]
Wasn't able to reproduce this issue using Windows 2003 Enterprise SP1 and the latest rdesktop (built from master branch).
Checked on Arch Linux + i3wm.
Fullscreen or not - no crash seen.

**Comment by trentasis** [comment]
My environment is a windows 2003 sp1 ro enterprise edition, but is not easy to reproducte this error only using a specific application and with specific menu. With windows 2012 works and windows 2003 and old rdesktop, for example 1.5 works.

Thanks

**Comment by uglym8** [comment]
Ok.
Now I've got both (r1/r2) w2k3 installation available.

Let's clarify this issue a bit:
So this error does only manifest itself while using specific application and specific menu from this application?
Right?
And this error occurs every time you use this application?
Is it possible to get this app to test this behaviour? 
Or it's proprietary and hence not redistributable?

TIA.
Regards.

**Comment by trentasis** [comment]
Correct, is reproduced sometimes in specific stuations
It is a propietary app

We will migrate to 2012 , for now we can close this issue

Thanks

2017-09-13 21:14 GMT+02:00 Alexander Zakharov <notifications@github.com>:

**Comment by uglym8** [comment]
Could you please close it then?
Or maybe @hean01-cendio can close it as an owner?
TIA.
