### ISSUE TITLE
rdesktop won't display password screen on Win7 -- prompts for password and suspends itself

### ISSUE THREAD

**Issue by joshudson** [rdesktop/rdesktop#151]
As of commit 17fa29c783b3e2f67c4307493f32a85f08404b10

I have no idea what's going on but rdesktop won't connect to my Win7 machine anymore. It just prompts for a password even without -p -. On resuming it with the fg command it doesn't seem to be wanting a password.

It got (uselessly) to the login screen of my windows 10 machine.

**Comment by uglym8** [comment]
Hi!
I'm sorry to ask such a stupid question but are you sure the your Win7 has remote access enabled?
I've just tested the most recent rdesktop (tip of the master branch) and it works without a glitch.
Can you elaborate a little bit more?
What DE?
What distro?
What exact cmd line you use to run rdesktop?

TIA.
Regards.

**Comment by joshudson** [comment]
I use Debian however I compiled that commit hash directly. RDP is enabled; the stored build from my "surge" branch of rdesktop works just fine.

**Comment by joshudson** [comment]
Command line: rdesktop -u username -g 1280x1000 ip-address. Desktop environment is KDE but I'm convinced that doesn't matter.

**Comment by hean01-cendio** [comment]
@joshudson I check out 17fa29c / build and connected to my win7 without any problems.

Can you post a strace when this happens, eg just till it hangs / suspends for investigation.

**Comment by joshudson** [comment]
On strace I finally noticed that the reason it's going into the background is I'm spawning it into the background.

For some reason it now tries to read a password all the time rather than only when given -p - which is the actual breaking change. The previous release also suspends if given -p - in the background.

Interesting output from strace:

close(3)                                = 0
fstat(1, {st_mode=S_IFREG|0644, st_size=20676, ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
write(2, "Password: ", 10Password: )              = 10
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
--- stopped by SIGTTOU ---
strace: Process 4623 detached

**Comment by hean01-cendio** [comment]
> Please note that this change makes it pretty much impossible to run rdesktop except in a terminal.

@joshudson kind of true, rdesktop does not have a graphical UI. Our intentions are to change that, meanwhile you can create a wrapper script which graphically prompts for a password and feeds it to rdesktop.

You will find reasoning on bug #80 for this change to always prompt for password.
