### ISSUE TITLE
Implement support for fragmented Fast-Path Updates

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#157]
This is required to support multi fragmented data transfers which in its turn is required for transferring large color pointers. This issue actually blocks the PR #66 which adds support for high dpi.

[Server Fast-Path Update PDU (TS_FP_UPDATE_PDU)](https://msdn.microsoft.com/en-us/library/cc240621.aspx)

**Comment by derfian** [comment]
iso.c seems to already detect the TS_FP_UPDATE_PDU headers, and support for fastpath updates is advertised through the general capabilityset. I'll keep digging through the code to see if I can make sense of it..

**Comment by derfian** [comment]
The rdpver parameter sent through the secure/mcs/iso/tcp layers actually does hold the information whether this is a fast-path update or not. So that's what it's for...

**Comment by derfian** [comment]
TS_FP_UPDATE_PDU packets end up in rdp5_process(). It doesn't look like it handles fragmentation though, so I suppose that's an issue to solve here.

**Comment by derfian** [comment]
Fragmented fast-path updates are enabled in PR #171.
