### ISSUE TITLE
Implement Suppress Output PDU

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#161]
The Suppress Output PDU is sent by the client to toggle all display updates from the server. This
packet does not end the session or socket connection. Typically, a client sends this packet when its
window is either minimized or restored. Server support for this PDU is indicated in the General
Capability Set (section 2.2.7.1.1).

**Comment by derfian** [comment]
`rdp_send_client_window_status` from rdp.c seems to handle exactly this. It's called when we get `MapNotify`/`UnmapNotify` events from the X Event loop.

**Comment by derfian** [comment]
Well, at least it handles sending the events. I don't think we care if the server advertises support for it or not.

**Comment by hean01-cendio** [comment]
Good catch and clenaup. Closing this issue then.
