### ISSUE TITLE
Auto-build rdesktop for OS X through Travis CI

### ISSUE THREAD

**Issue by derfian** [rdesktop/rdesktop#163]

**Comment by uglym8** [comment]
I've already added this to my test branch (https://github.com/uglym8/rdesktop/tree/mac_build) but free OS X Travis  boxes are really slow to startup (up to 1hour  just to boot up) so I decided not to add this until it's fixed.
Also check this issue https://github.com/travis-ci/travis-ci/issues/7304

**Comment by derfian** [comment]
That's too bad. I hope the situation improves so we can use Travis for this in the future.

**Comment by uglym8** [comment]
Actually maybe we can still use it.
If everyone agrees that long (compared to linux) build time for OSX is OK then why not.
This amount of time is still less than the average merge time (time which needed to review and merge PR) anyway.

**Comment by hean01-cendio** [comment]
I tend to agree, its just one hour :), lets add that.

**Comment by uglym8** [comment]
So be it:)

**Comment by uglym8** [comment]
I mentioned previously the long (around 1 hour) time taken to boot Travis CI OSX image.
Last build took only 4 m 34 s so it's seems that it's not true anymore.
