### ISSUE TITLE
Sometimes mouse pointers disappears

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#165]
I have found the following cases:

- When connecting to a RDS and provides the wrong password, but only sometimes
- When changing to shadowed mouse cursor
- When using high DPI as in #66 above a certain dpi setting

This is not a regression with the changes made for supporting alpha cursors.
What I have seen is that there is no cursors sent from server. This is also the
same case when server is using LARGE_POINTER_CURSORS (96x96) eg. pointers
bigger then 32x32, for example when a high DPI is used, which is a capability
that rdesktop does not implement.

This absence of LARGE_POINTER capability could also be the the reason we do not
get cursors from server when cursor shadow is enabled. Based on the assumption
that adding shadows to a cursors 32x32 cursor would probably requires a bigger
cursor than 32x32 cursors.

See #157 for implementing Fast-Path which is required for LARGE_POINTERs

**Comment by derfian** [comment]
For case 1, the login screen on an RDS, this statement is not true:

> What I have seen is that there is no cursors sent from server.

The RDS sends a Fast-Path System Pointer Default Update ([MS-RDPBCGR] 2.2.9.1.2.1.6) that rdesktop reads but ignores.

**Comment by hean01-cendio** [comment]
When then rdp client does not announce large pointer support, the server will send system default pointer messages which is ignored by rdesktop. PR #170 will handle those and set default local mouse pointer and therefor fix the problem that no mouse pointer are shown at all.

**Comment by derfian** [comment]
I've moved the large pointer issue to #173. I believe we've solved all the remaining issues here through PR #170.
