### ISSUE TITLE
How to disable mouse over border switching? 

### ISSUE THREAD

**Issue by zimonth** [rdesktop/rdesktop#169]
Not really an issue,but a question and possible feature request.

I have two Fedora Linux machines, where I use rdesktop to share keyboard and mouse between them. I do not have two monitors, but just one monitor with DVI-D and DP connectors with two PC*s conneted to them.

Often I accidentally (for example in Unreal Engine Editor Play mode) roll over to other side and there go to hot corner to the GNOME menu and after that I cannot get mouse and keyboard back, or do not succeed blindly, but have to switch from the monitor's menu buttons between DVI-D and DP.

I would be happy, if I could disable whole rover over border switch feature in rdesktop and only use keyboard shortcuts, like CTRL+ALT+right/left-arrow keys to switch computers.

Is this possible now somehow?

**Comment by hean01-cendio** [comment]
Correct me, if I  have understanded your problem wrong; you are running rdesktop in windowed mode and then accidental moves mouse out from rdesktop window and hits the GNOME hot corner which steals the focus from your rdesktop window. When this happens you lose input and is not possible to get focus back into rdesktop window ?

Does it work by clicking into rdesktop window to recapture the focus ?

**Comment by zimonth** [comment]
You have understood correctly. 
When sometimes (and not so rarely) mouse wanders to the wrong screen (the server's which has GNOME), and then when I try to get the pointer back to client's screen, I accidentally have hit GNOME hot corner and it is in GNOME menu. Now the mouse pointer and keyboard focus does not come back anymore, unless I blindly get out of the GNOME menu and then roll to the screen I want.

I have had this now so many times, it would seem like a good idea just to be able to disable that over the side switching feature and just use keyboard shortcuts to switch screens.

**Comment by zimonth** [comment]
Hey! Sowwwy!
I have mixed up rdesktop and synergy in my head. It is a problem with Synergy (synergys,synergyc) that when mouse goes accidentally behind GNOME-Menu, it is practically impossible to get back so it would switch to the client (synergyc) machine back.

I use both rdesktop and synergy to manage these two machines with one console (kb+mouse+monitor) and got mixed up which causes what.
