### ISSUE TITLE
High multicast traffic with scard support and nlb multicast cluster

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#18]
Hi,

We were using rdesktop 1.6 and smartcard support with a cluster of TS servers (nlb  with multicast mode) and was working perfect.

Now we have upgraded to latest version (1.8.3) but we have detected that with this version a high multicast traffic is generated and this has caused network problems and all local network, and then we can't work and we have many networks problems.

After some test we have detected:
- Problem reproduced with 1.8.3, 1.8.0, and 1.7.1 and also with latest version -master branch-
- With 1.6 works perfect
- this only is reproduced when rdesktop is used with ip of nlb cluster and smartcard support is used "-r scard"

If we use rdesktop nlb but without smartcard (-r scard) then works, but we can work with smartcard

It seems that problems is with smartcard support and multicast nlb, but we don't know where is the problema and how can I solve this...

Anybody can help? How can I solve this?

Attached pcap files with 1.6 and 1.8.3

[rdesktop1_8_3_ERROR.txt](https://github.com/rdesktop/rdesktop/files/49780/rdesktop1_8_3_ERROR.txt)
[rdesktop1_6_OK.txt](https://github.com/rdesktop/rdesktop/files/49781/rdesktop1_6_OK.txt)
##

**Comment by hean01-cendio** [comment]
Gah, the above commit is a fix for issue #8

**Comment by trentasis** [comment]
windows 2003 end of support, discard  this issue
Thanks
