### ISSUE TITLE
Password sent in the username field in clear text then logged by windows

### ISSUE THREAD

**Issue by nathanshearer** [rdesktop/rdesktop#181]
When logging into a Windows Server 2012 and selecting "Other user", I select the password field with my mouse and begin typing my password. The focus has automatically returned back to the username field and now my password is being entered into the username field instead! Now when I press enter it is logged by windows in clear text.

When I connect to a Windows Server 2012 host with the "-u username" option, I am given two tiles to select: one with my username and "Other user". If I select the one with my username it only allows logging in with a smart card, so I never use that tile. Instead I always select "Other user". My username is already populated in the "Other user" tile so all I have to enter is my password to login. At first the Username field has focus, but if you select the password field the focus immediately returns to the Username field.

Typically users will select the password field, type their password, and press enter. And if they are not paying really close attention they will encounter this bug.

When selecting "Other user" there is a slight animation where the screen fades in and pans to the left. If you wait for that animation to stop, then select the password field, the focus will remain in the password field. If you select the password field while the animation is finishing it's slow pan then the focus immediately returns to the username field.

This is reproducible on a fresh and fully updated Windows Server 2012 host.

**Comment by nathanshearer** [comment]
Looks like it's not a bug in rdesktop.

**Comment by hean01-cendio** [comment]
Great, that was my thought, that's why i didn't answer up on the issue before i could try it using the windows rdp client.
