### ISSUE TITLE
Toggling full screen does not resize session

### ISSUE THREAD

**Issue by derfian** [rdesktop/rdesktop#192]
When we enter/leave full screen, the session size is left untouched. This often leads to unwanted black borders around the session contents after entering full screen.

**Comment by derfian** [comment]
We have observed the Microsoft client resize the session so it looks like a possible task. We analyzed the network traffic and found a monitor layout message that resized the session. This message is described in MS-RDPEDISP.

**Comment by derfian** [comment]
MS-RDPEDISP requires Dynamic Virtual Channels, described in MS-RDPEDYC.

**Comment by derfian** [comment]
We could probably also use this new found message instead of the `g_pending_resize` disconnect-reconnect way of resizing the session.

**Comment by uglym8** [comment]
ATM I'm working on the implementation of MS-RDPEDYC support (as it's a prerequisite for MS-RDPEAI), so I hope that in a couple of days there will be the appropriate PR.

As for MS-RDPEAI: I can already redirect local microphone and record voice/use skype.
Need to clean up/conduct some tests (mostly latency related) though.

**Comment by derfian** [comment]
We've got code for MS-RDPEDYC working and our intentions is to commit it today together with a basic MS-RDPEDISP implementation. Our intentions has been to provide a simple API to the Dynamic Virtual Channels so other protocols can be implemented on top of it.

**Comment by uglym8** [comment]
That was also my goal too:)

**Comment by derfian** [comment]
MS-RDPEDISP is supported on Windows 8.1, Windows Server 2012 R2 and newer.

**Comment by derfian** [comment]
Dynamic Virtual Channels (MS-RDPEDYC) are supported on Windows Vista, Windows Server 2008 and newer.
