### ISSUE TITLE
Fooo! messagem printed in console

### ISSUE THREAD

**Issue by alexandrevicenzi** [rdesktop/rdesktop#199]
rdesktop keeps printing Fooo! in the console. I found a way to reproduce easily by just navigating on Windows Explorer, almost every time I enter a new folder it prints Fooo!.

At first I thought that it was some random message in the code, but I couldn't find this message in rdesktop code. My guess is that the remote server sends this message and rdesktop just print it.

rdesktop version: 1.8.3
host: openSuse Leap 42.2
remote: Windows 7

```
alexandre@suse ~ $ rdesktop -rsound:local -g 1600x960 -u adm -P 192.168.1.101
ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?
Connection established using SSL.
WARNING: Remote desktop does not support colour depth 24; falling back to 16
ERROR: RDPSND: Extra RDPSND_NEGOTIATE in the middle of a session
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
Fooo!
WARNING: No translation for (keysym 0x1008ff14, XF86AudioPlay)
WARNING: No translation for (keysym 0x1008ff14, XF86AudioPlay)
```

**Comment by uglym8** [comment]
Hi, 
can you checkout, build and try the most recent version, please?

**Comment by alexandrevicenzi** [comment]
@uglym8 building master I can't reproduce the error anymore, but I get other errors.

```
 $ ./rdesktop -rsound:local -g 1600x960 -u amd -P 192.168.1.101
Connection established using SSL.
Protocol(warning): process_pdu_logon(), Unhandled login infotype 1
Clipboard(error): xclip_handle_SelectionNotify(), unable to find a textual target to satisfy RDP clipboard text request
Sound(error): oss_open(), open() failed: No such file or directory
```

I build with `--disable-credssp` because I couldn't find the lib for openSuse, not sure if these errors are related to this flag.

**Comment by uglym8** [comment]
Nope, they are not related.
Can you hear the sound?
If not, try to use **-r sound:local:alsa** and/or check #142

**Comment by alexandrevicenzi** [comment]
I can't hear any sound even with ALSA.

**Comment by uglym8** [comment]
Ok.
Can you hear the sound if you try to run rdesktop with padsp?
i.e.
````bash
$ padsp rdesktop your_rdesktop_options

**Comment by alexandrevicenzi** [comment]
I can hear if I use Pulse, but with ALSA does not work also.

Work: `padsp ./rdesktop -rsound:local -g 1600x960 -u amd -P 192.168.1.101`
Does not Work:`padsp ./rdesktop -rsound:local:alsa -g 1600x960 -u amd -P 192.168.1.101`

**Comment by alexandrevicenzi** [comment]
Well, looks like both works with padsp.

**Comment by uglym8** [comment]
Great.
You can also check PR #152 for PulseAudio support (don't use **padsp** when checking though:)

**Comment by alexandrevicenzi** [comment]
Since this issue was fixed I'm closing this.
