### ISSUE TITLE
Rdesktop do not connect to server if security disclaimer is shown

### ISSUE THREAD

**Issue by ViachaslauKabak** [rdesktop/rdesktop#202]
If security disclaimer is set on remote windows server - rdesktop does not establish the connection to such server

**Comment by uglym8** [comment]
Hi!
You're talking about this https://technet.microsoft.com/en-us/library/dd277405.aspx?
What Windows server version did you try?

**Comment by ViachaslauKabak** [comment]
Hi,
I'm talking about that https://social.technet.microsoft.com/Forums/windows/en-US/d1d0af50-cb9a-4204-a19c-4a9ecaf1cfb7/logon-disclaimer-in-windows-7?forum=w7itprosecurity
Using win7 and Winserver 2016
Security disclaimer is configured by group policy - so there is no chance to disable it

**Comment by uglym8** [comment]
I've set **"Interactive logon: Message text for users attempting to log on"** and **"Interactive logon: Message title for users attempting to log on"** on Windows 10.

I can connect using either Microsoft native RDP client (from Win7) or the most recent rdesktop.

Either way I've got the dark blue screen with the text I entered in Group Policy and "OK" button.
Clicking this button allows me to login (assuming, of course, that the supplied login/password pair is correct).

**Comment by ViachaslauKabak** [comment]
could you please try to connect from linux machine via rdesktop from command line?
I have found one workaround for such problem
http://opentechnotes.blogspot.com.by/2014/03/automatic-rdesktop-logon-linux.html

**Comment by uglym8** [comment]
>  I can connect using either Microsoft native RDP client (from Win7) or **the most recent rdesktop**.
![screenshot](https://user-images.githubusercontent.com/14952529/33212159-de2ef718-d132-11e7-8c46-65fb61127edf.jpg)

**Comment by ViachaslauKabak** [comment]
but what about linux commandline?

**Comment by uglym8** [comment]
Hi, 
the picture above was taken when I connected via rdesktop (**obviously** from command line) on **Linux**
to **Windows 10**.
I got the **same** result as connecting via native Microsoft client.

Do you have difficulties when connecting to **Win7**?
Or only in a case of **W2K16**?
What version of rdesktop you're using?

**Comment by ViachaslauKabak** [comment]
We have no UI on linux - so there is no possibility to press button

**Comment by uglym8** [comment]
What do you exactly mean by "We have no UI on linux"?
You mean that no graphics shown at all?

And if you disable the security disclaimer you can connect to this host, right?
Or you've no control over this server?

Could you, please, answer to these questions as well:
Do you have difficulties when connecting to Win7?
Or only in a case of W2K16?
What version of rdesktop you're using?

**Comment by ViachaslauKabak** [comment]
no graphics at all - only bash condole
if to disable security disclaimer - we can connect (tried on the same server)
Answers:
1. cannot connect both win7 and server 2016
2. latest rdesktop 1.8.3

**Comment by uglym8** [comment]
Could you, please, build the most recent version of rdesktop (from master's source) and verify that the problem persists?
Thank you.

**Comment by uglym8** [comment]
Closing due to no response
