### ISSUE TITLE
undefined reference OPENSSL_init_ssl on make

### ISSUE THREAD

**Issue by markd89** [rdesktop/rdesktop#207]
Hi,

I'm trying to build from source so  that I can use this patch (https://github.com/rdesktop/rdesktop/commit/2a6298ac63e9db2449a691e17f176b7bf6a7638f). I am on Debian Jessie.

./configure finishes OK

make does this:

gcc -g -O2 -Wall -I/usr/include -I/usr/include/gssglue   -pthread -I/usr/include/PCSC   -I/usr/include/alsa   -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3post\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3post\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"/usr\" -DWITH_CREDSSP=1 -DHAVE_XRANDR=1 -DWITH_SCARD=1 -DEGD_SOCKET=\"/var/run/egd-pool\" -DWITH_RDPSND=1 -DRDPSND_OSS=1 -DRDPSND_ALSA=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_VFS_H=1 -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DHAVE_STRUCT_STATFS_F_NAMELEN=1 -DHAVE_MNTENT_H=1 -DHAVE_SETMNTENT=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o rdesktop rdesktop.o xwin.o xkeymap.o ewmhints.o xclip.o cliprdr.o ctrl.o rdpsnd.o rdpsnd_dsp.o rdpsnd_oss.o rdpsnd_alsa.o tcp.o asn.o iso.o mcs.o secure.o licence.o rdp.o orders.o bitmap.o cache.o rdp5.o channels.o rdpdr.o serial.o printer.o disk.o parallel.o printercache.o mppc.o pstcache.o lspci.o seamless.o ssl.o utils.o scard.o cssp.o -L/usr/lib -L/usr/lib64 -lssl -lcrypto -ldl  -lgssglue -lXrandr  -lpcsclite   -lasound     -lX11
**tcp.o: In function `tcp_tls_connect':

/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:305: undefined reference to `OPENSSL_init_ssl'
/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:306: undefined reference to `OPENSSL_init_ssl'
/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:325: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'rdesktop' failed
make: *** [rdesktop] Error 1**

Any suggestions how to fix much appreciated!

Mark

**Comment by uglym8** [comment]
Hi, Mark!

I've just checked the build of  the latest rdesktop using Debian Jessie docker image
````
$ cat /etc/debian_version
8.10

$ dpkg -l|grep ssl
ii  libssl-dev:amd64            1.0.1t-1+deb8u7                  amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                  1.0.1t-1+deb8u7                  all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64           1.0.1t-1+deb8u7                  amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                     1.0.1t-1+deb8u7                  amd64        Secure Sockets Layer toolkit - cryptographic utility

````
Your linking stage line looks like this:
````
 -L/usr/lib -L/usr/lib64 -lssl -lcrypto -ldl -lgssglue -lXrandr -lpcsclite -lasound -lX11
````
whereas mine:
````
 -L/usr/lib -L/usr/lib64 -lssl -lcrypto -ldl  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lgssapi_krb5  -lXrandr  -lXcursor  -lpcsclite      -lX11
````
Check that you use the correct  SSL *-dev libs.

One more hint:
Use **libkrb5-dev** instead of **libgsslue**

**Comment by markd89** [comment]
Thanks for your help.

I removed libgssglue and when I ./configure I got:

CredSSP support requires libgssglue, install the dependency or disable the feature using --disable-credssp.

I don't need smart card support so I configured again with ./configure --disable-smartcard --disable-credssp and it completed OK.

I did check the libssl versions and they are the same as yours.

I installed libkrb5-dev, but when I run make, I don't see that being included on the linker line. Is there maybe another parameter I need to use on configure?

gcc -g -O2 -Wall -I/usr/include   -I/usr/include/alsa   -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3post\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3post\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"/usr\" -DHAVE_XRANDR=1 -DEGD_SOCKET=\"/var/run/egd-pool\" -DWITH_RDPSND=1 -DRDPSND_OSS=1 -DRDPSND_ALSA=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_VFS_H=1 -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DHAVE_STRUCT_STATFS_F_NAMELEN=1 -DHAVE_MNTENT_H=1 -DHAVE_SETMNTENT=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o rdesktop rdesktop.o xwin.o xkeymap.o ewmhints.o xclip.o cliprdr.o ctrl.o rdpsnd.o rdpsnd_dsp.o rdpsnd_oss.o rdpsnd_alsa.o tcp.o asn.o iso.o mcs.o secure.o licence.o rdp.o orders.o bitmap.o cache.o rdp5.o channels.o rdpdr.o serial.o printer.o disk.o parallel.o printercache.o mppc.o pstcache.o lspci.o seamless.o ssl.o utils.o   -L/usr/lib -L/usr/lib64 -lssl -lcrypto -ldl  -lXrandr   -lasound     -lX11
tcp.o: In function `tcp_tls_connect':
/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:305: undefined reference to `OPENSSL_init_ssl'
/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:306: undefined reference to `OPENSSL_init_ssl'
/mnt/hgfs/debian8vmtemp/rdesktop/ex/tcp.c:325: undefined reference to `SSL_CTX_set_options'
iso.o: In function `iso_connect':
/mnt/hgfs/debian8vmtemp/rdesktop/ex/iso.c:325: undefined reference to `cssp_connect'
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'rdesktop' failed
make: *** [rdesktop] Error 1


Thanks!
Mark

**Comment by derfian** [comment]
Mark, just to make sure we're all on the same page - are you using the latest release (1.8.3) or a clone of the git repo?

**Comment by markd89** [comment]
Apologies for my ignorance...

I was trying to build including this patch https://github.com/rdesktop/rdesktop/commit/2a6298ac63e9db2449a691e17f176b7bf6a7638f

so I went here:
https://github.com/rdesktop/rdesktop/tree/2a6298ac63e9db2449a691e17f176b7bf6a7638f 
then selected Clone or Download then Download ZIP.

Should I be doing something else?

Thanks,
Mark

**Comment by derfian** [comment]
I see, thanks for clarifying!

The patch you are referring was committed to rdesktop on 2015, so any later version would include it. I think you're better off building with the latest 1.8.3 release, or even building from the latest git master - it's been a while since we did a release and there's quite a few neat features and fixes that hasn't made it into a proper release yet.

**Comment by uglym8** [comment]
@derfian, thank you for clarification:) at first thought that it was redundant but alas:)
@markd89, could you please just:
````bash 
$ git clone https://github.com/rdesktop/rdesktop.git
````
and try to build it again

**Comment by markd89** [comment]
Gents, thanks very much. Much easier and all working!
