### ISSUE TITLE
Local mouse cursor

### ISSUE THREAD

**Issue by joshudson** [rdesktop/rdesktop#21]
I have an application (that unfortunately I will not be able to provide) that causes the rdesktop mouse cursor to disappear but windows remote desktop cursor to remain. It looks from the changelog an attempt was made to fix it. It just made it happen less often. :(

I've had other issues with remote cursors where sometimes a cursor + background combination is really bad.

Would it be feasible to add a command line option to force use of local mouse cursor rather than remote mouse cursor?
##

**Comment by hean01-cendio** [comment]
@joshudson, could you test the latest rdesktop source to see if that solves this issue.

**Comment by joshudson** [comment]
I am pondering what to do because the linux remote desktop server doesn't have Xrender extensions. So guess what happens when I have to stack rdesktop instances?

I suppose we could auto-detect now when local mouse is necessary.

**Comment by joshudson** [comment]
Update: cursor issue *not* fixed. I'm posting details to #86.

**Comment by hean01-cendio** [comment]
@joshudson I choosed to use libXcursor which uses fallbacks for Xservers without Xrender extension, still haven't tested that out. Could you post some screenshot crops for different cursors.

**Comment by joshudson** [comment]
So I am pondering between two choices. I haven't tried the latest mouse changes but I expect they work. Either I can put -M back for local mouse cursor or I can switch on local mouse cursor with -m which will always need it.

I would not have discovered -m needing local mouse cursor early because I did not use -m in production until I had to squash lag from high DPI.

**Comment by joshudson** [comment]
Come to think of it I don't know what will happen if Xrander isn't there (i.e. nested rdesktop).

**Comment by hean01-cendio** [comment]
> Come to think of it I don't know what will happen if Xrander isn't there (i.e. nested rdesktop)

I assume you mean Xrender and that context is related to when using remote cursors. libXcursor uses a fallback when the Xrender is not available. I haven't tested this and do not how the results are.

**Comment by hean01-cendio** [comment]
> So I am pondering between two choices. I haven't tried the latest mouse changes but I expect they work. 
Either I can put -M back for local mouse cursor or I can switch on local mouse cursor with -m which will
always need it.

I think the '-M' approach is the correct way to go. The '-m' feature will have problems with some application which expects motion events and there for, local mouse pointer feature will be broken in
such case.

**Comment by joshudson** [comment]
Pull request #182 didn't auto-link :(

**Comment by hean01-cendio** [comment]
Commit e7cda3dbf adds support for local cursor
