### ISSUE TITLE
make for 1.8.3 fails on Kali rolling

### ISSUE THREAD

**Issue by rfrogman** [rdesktop/rdesktop#215]
I am having issues compiling rdesktop v1.8.3 on Kali Rolling to support rdp2tcp. I am receiving openssl errors (see below) during the make process.

Distro: 4.14.0-kali1-amd64
OpenSSL 1.1.0g  2 Nov 2017

I ran the following options from the configure file.

./configure --disable-credssp --disable-smartcard --with-openssl=/usr

make
gcc -g -O2 -Wall -I/usr/include   -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"/usr\" -DEGD_SOCKET=\"/var/run/egd-pool\" -DWITH_RDPSND=1 -DRDPSND_OSS=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_VFS_H=1 -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DHAVE_STRUCT_STATFS_F_NAMELEN=1 -DHAVE_MNTENT_H=1 -DHAVE_SETMNTENT=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o ssl.o -c ssl.c
ssl.c: In function ‘rdssl_rsa_encrypt’:
ssl.c:92:9: error: storage size of ‘mod’ isn’t known
  BIGNUM mod, exp, x, y;
         ^~~
ssl.c:92:14: error: storage size of ‘exp’ isn’t known
  BIGNUM mod, exp, x, y;
              ^~~
ssl.c:92:19: error: storage size of ‘x’ isn’t known
  BIGNUM mod, exp, x, y;
                   ^
ssl.c:92:22: error: storage size of ‘y’ isn’t known
  BIGNUM mod, exp, x, y;
                      ^
ssl.c:102:2: warning: implicit declaration of function ‘BN_init’; did you mean ‘ui_init’? [-Wimplicit-function-declaration]
  BN_init(&mod);
  ^~~~~~~
  ui_init
ssl.c:92:22: warning: unused variable ‘y’ [-Wunused-variable]
  BIGNUM mod, exp, x, y;
                      ^
ssl.c:92:19: warning: unused variable ‘x’ [-Wunused-variable]
  BIGNUM mod, exp, x, y;
                   ^
ssl.c:92:14: warning: unused variable ‘exp’ [-Wunused-variable]
  BIGNUM mod, exp, x, y;
              ^~~
ssl.c:92:9: warning: unused variable ‘mod’ [-Wunused-variable]
  BIGNUM mod, exp, x, y;
         ^~~
ssl.c: In function ‘rdssl_cert_to_rkey’:
ssl.c:150:24: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                        ^~
In file included from ssl.h:27:0,
                 from ssl.c:22:
ssl.c: In function ‘rdssl_rkey_get_exp_mod’:
ssl.c:205:24: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
  if ((BN_num_bytes(rkey->e) > (int) max_exp_len) ||
                        ^
ssl.c: In function ‘rdssl_hmac_md5’:
ssl.c:233:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;
           ^~~
ssl.c:234:2: warning: implicit declaration of function ‘HMAC_CTX_init’; did you mean ‘HMAC_CTX_new’? [-Wimplicit-function-declaration]
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
  HMAC_CTX_new
ssl.c:236:2: warning: implicit declaration of function ‘HMAC_CTX_cleanup’; did you mean ‘HMAC_CTX_get_md’? [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
  HMAC_CTX_get_md
ssl.c:233:11: warning: unused variable ‘ctx’ [-Wunused-variable]
  HMAC_CTX ctx;
           ^~~
Makefile:161: recipe for target 'ssl.o' failed
make: *** [ssl.o] Error 1

**Comment by hean01** [comment]
This should be fixed with PR #44, try build rdesktop from source to verify.

**Comment by rfrogman** [comment]
I am confused by your response. The errors I posted above are from trying to "make" the latest source for rdesktop v1.8.3. Your response is to do the same thing I am having issues with.

**Comment by uglym8** [comment]
Hi @rfrogman,
what @hean01 meant to say is: try to clone the repository by 
````
git clone https://github.com/rdesktop/rdesktop.git
````
and build these sources.

I've too got the impression that you're having these errors because
 you're trying to build the most recent **release** tarball i.e. 
https://github.com/rdesktop/rdesktop/releases/tag/v1.8.3

**Comment by rfrogman** [comment]
Ah, thank you for the clarification. Due to the holiday it will be next week before I can retest. Thank you for the response.

**Comment by rfrogman** [comment]
git clone https://github.com/rdesktop/rdesktop.git version allowed me to make the file but now the oop-1.8.1.patch for rdp2tcp fails which is not your guys issue.
