### ISSUE TITLE
rdesktop on low network speeds (-z -P -x)

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#226]
Hi,

I have some clients with low network speed (remote office), and trying to migrate this clients from widnwos 2003 to windows 2012, we detected that same client and network speed, now with windows 2012 all works very slow!!! 

I'm trying to optimize rdesktop perofrmance with some parameteres like 
-z -P or -x

Now I'm trying -z and -P, but -P generate error that can't generate mkdir, manually I can generate folders in /tmp... but I don't know why show this error, where and when try to generate a folder, and what user?

What is the best parameters for low speed networks? -x is not clear for me what is the result, anybody can give some details?

Thanks

**Comment by uglym8** [comment]
Hi!
1) You can use **"-x"** option with the following arguments:
**m, b, l** or **hex numeric values**
**m** means "**modem**"
**b** means "**broadband**"
**l** means **LAN**

So you can try to use "**-x m**" to use low bandwidth features.
See if it helps.

2) Regarding persistent bitmap caching (**-P**):
Bitmap caches are stored in **$HOME/.rdesktop/cache**.
Could you please post the mkdir() error you're talking about.

**Comment by trentasis** [comment]
Hi,
What is the best practices in low networks -x m -z -P, 3 options at same time? any other suggestion?

It seems that my distribution generates $HOME/.rdesktop file (not folder), not sure why? I can remove this file safely to work correctly or this can generate any issue?

Thanks

**Comment by uglym8** [comment]
Hi,
unfortunately, off the top of my head I can't come up with somewhat meaningful combination of options to alleviate the slowness of your connection.


I'd try to use "**-x m**" (maybe with **-z**). 
Did you try to use it? 
What was the result?
Was it tolerable or still slow to use?

Guys (@hean01-cendio, @derfian),  could suggest something else here?

Regarding mkdir() issue:
1) Could please specify what Linux distro you're using?
I want to check this issue myself.
2) What does the following command show?
````
$ echo $HOME
````

3) Am I getting you right that rdesktop generates file instead of the directory?
**$HOME/.rdesktop** is a file?
What happens if you delete this file and run rdesktop again (with **-P** option, of course)

**Comment by hean01-cendio** [comment]
> Guys (@hean01-cendio, @derfian), could suggest something else here?

I would look into group policies for turning down theme based graphical features in a session, like menu animation, fading, alpha channels etc. to reduce the amount of graphic traffic that is generated. I know that there are many best practices [1] on this topic were you will find good info on the subject.

Some of the above mentioned settings are controllable via RDP protocol and rdesktop supports them with the earlier mentioned  ```-x``` argument.

[1] https://msdn.microsoft.com/en-us/library/windows/hardware/dn567648(v=vs.85).aspx

**Comment by trentasis** [comment]
Thanks great info, evaluating results...

**Comment by trentasis** [comment]
It seems that using -z -P -x m graphics performance is better! Thanks

But the issue detected is with smartcards using -r scard from a ADSL with 60ms it shows many errors with in debug mode

Protocol(debug): rdpdr_send_completion()
Protocol(debug): channel_send(), length = 100
Protocol(debug): channel_send(), sending 100 bytes with FLAG_FIRST set
Protocol(debug): rdpdr_process()
SmartCard(debug): TS_SCardGetStatusChange(), context: 0x00000010 [0x11afd155], timeout: 0x000003e8, count: 1
SmartCard(debug): TS_SCardGetStatusChange(), reader='Cherry KC 1000 SC [KC 1000 SC] 00 00', user=(nil), state=6012200060122, event=0x00313520
Protocol(debug): rdpdr_process()
SmartCard(debug): TS_SCardGetStatusChange(), context: 0x0000000e [0x3eb51666], timeout: 0x0000ea60, count: 1
SmartCard(debug): TS_SCardGetStatusChange(), reader='\\?PnP?\Notification', user=(nil), state=100000000, event=0x00000000
SmartCard(debug): TS_SCardGetStatusChange(), success
SmartCard(debug): TS_SCardGetStatusChange(), reader='\\?PnP?\Notification', user=(nil), state=100000000, event=0x00000000
Protocol(debug): rdpdr_send_completion()
Protocol(debug): channel_send(), length = 100
Protocol(debug): channel_send(), sending 100 bytes with FLAG_FIRST set
Protocol(debug): rdpdr_process()
SmartCard(debug): TS_SCardGetStatusChange(), context: 0x0000000e [0x3eb51666], timeout: 0x0000ea60, count: 1
SmartCard(debug): TS_SCardGetStatusChange(), reader='\\?PnP?\Notification', user=(nil), state=100000000, event=0x00000000
SmartCard(debug): TS_SCardGetStatusChange(), success
SmartCard(debug): TS_SCardGetStatusChange(), reader='\\?PnP?\Notification', user=(nil), state=100000000, event=0x00000000
Protocol(debug): rdpdr_send_completion()
Protocol(debug): channel_send(), length = 100
Protocol(debug): channel_send(), sending 100 bytes with FLAG_FIRST set
Protocol(debug): rdpdr_process()

Same rdesktop command using from local network issue is not reproduced (<1ms), tried with windows 2003 and also with windows 2012r2, with widnwos 2003 you can work, but seems that with widnows 2012r2  is not working and you can't work with smartcards

If I have to collect more information or open another case, I can do.

Thanks
