### ISSUE TITLE
No window when the broker redirects to another 2012R2 TSE of a collection using NLA authentification

### ISSUE THREAD

**Issue by gilbsfr24** [rdesktop/rdesktop#228]
I have 3 servers (1 broker 2012r2 & 2 RDS 2012R2 with NLA authentification. _(credssp)_)
When I want reconnect to my session the redirection does not open any window.

Command line 
rdesktop serverIp1 -u user -d domain  
my session was previously opened on serverIp2

if I call 
rdesktop serverIp2 -u user -d domain  
then no redirection and the desktop opens asking me my password after an error message "incorrect password"

"kinit user" command line has been done

**Comment by hean01-cendio** [comment]
You need to provide a password via command line. See bug #8 for more information on the topic.

**Comment by gilbsfr24** [comment]
Hi
Ok for the password

But what can we do for the problem of the window that does not appear. Because the program is still running

**Comment by hean01-cendio** [comment]
I'm sorry for missing that detail :). That is strange, nothing I have seen once, against our 2012r2 cluster.

With what version of rdesktop are you seeing this behavior ?

**Comment by gilbsfr24** [comment]
version 1.8.3

**Comment by hean01-cendio** [comment]
Is the problem reproducible using a build from source (HEAD) ?

If so, could you provide a debug log:

```
RDESKTOP_DEBUG=Core,UI rdesktop -v server -u user -d domain
```

**Comment by hean01-cendio** [comment]
When debugging another issue (X11 BadMatch) error is noticed that sometimes i got the X11 error and sometimes no window shown, just like your described. Fixed in a6d8261. Could you verify that this commit solved your issue ?

**Comment by gilbsfr24** [comment]
logs: direct I was on server1

./rdesktop server1 -u xxx -d xxx-p xxx
Autoselecting keyboard map 'fr' from locale
UI(debug): Performance optimization possible: avoiding image translation (colour depth conversion)
UI(debug): RDP depth: 16, display depth: 16, display bpp: 16, X server BE: 0, host BE: 0

Core(debug): dvc_channels_add(), Added hash=67f73722, channel_id=-1, name=Microsoft::Windows::RDS::DisplayControl, handler=0x8082bf0
Connecting to server using NLA...
Connection established using CredSSP.
UI(debug): ui_create_window() width = 1024, height = 768
UI(debug): ui_create_cursor(): xhot=0, yhot=0, width=1, height=1, bpp=24
UI(debug): ui_resize_window(), Changing window 1024x741 to match new session 1024x768 size
Connection successful
UI(debug): xwin_process_events(), Window mapped with size 1024x768
UI(debug): xwin_process_events(), ConfigureNotify: session: 1024x768, new window: 1024x768 (adj: 1024x768)
UI(debug): xwin_process_events(), ConfigureNotify: session: 1024x768, new window: 1024x741 (adj: 1024x741)
UI(debug): xwin_process_events(), ConfigureNotify: session: 1024x768, new window: 1024x741
UI(debug): xwin_process_events(), ConfigureNotify: session: 1024x768, new window: 1024x768 (adj: 1024x768)
UI(debug): ui_create_cursor(): xhot=10, yhot=10, width=32, height=32, bpp=1
UI(debug): ui_set_cursor(): g_current_cursor = (nil), new = 0x80000f
UI(debug): ui_create_cursor(): xhot=10, yhot=10, width=32, height=32, bpp=1
UI(debug): ui_set_cursor(): g_current_cursor = 0x80000f, new = 0x800013
UI(debug): ui_set_cursor(): g_current_cursor = 0x800013, new = 0x80000f
UI(debug): ui_set_cursor(): g_current_cursor = 0x80000f, new = 0x800013
UI(debug): ui_create_cursor(): xhot=10, yhot=10, width=32, height=32, bpp=1
UI(debug): ui_set_cursor(): g_current_cursor = 0x800013, new = 0x800017
UI(debug): ui_set_cursor(): g_current_cursor = 0x800017, new = 0x80000f
UI(debug): ui_set_cursor(): g_current_cursor = 0x80000f, new = 0x80000f
UI(debug): ui_set_cursor(): g_current_cursor = 0x80000f, new = 0x80000f
Protocol(warning): process_pdu_logon(), Unhandled login infotype 1
UI(debug): ui_set_cursor(): g_current_cursor = 0x80000f, new = 0x800013
UI(debug): ui_set_cursor(): g_current_cursor = 0x800013, new = 0x80000f
Established dynamic virtual channel 'Microsoft::Windows::RDS::DisplayControl'
Core(debug): dvc_channels_set_id(), name = 'Microsoft::Windows::RDS::DisplayControl', channel_id = 9

**Comment by gilbsfr24** [comment]
logs: with redirect - I was on server1

./rdesktop server2 -u xxx -d xxx-p xxx
Autoselecting keyboard map 'fr' from locale
UI(debug): Performance optimization possible: avoiding image translation (colour depth conversion)
UI(debug): RDP depth: 16, display depth: 16, display bpp: 16, X server BE: 0, host BE: 0

Core(debug): dvc_channels_add(), Added hash=67f73722, channel_id=-1, name=Microsoft::Windows::RDS::DisplayControl, handler=0x8082bf0
Connecting to server using NLA...
Connection established using CredSSP.
Redirected to test@172.31.1.202 session 4.
Connecting to server using NLA...
Connection established using CredSSP.

**Comment by gilbsfr24** [comment]
the Fix in a6d8261. does not solve the issue

**Comment by hean01-cendio** [comment]
@gilbsfr24 Thanks, now I see why you have some problem. In all my cases when connecting to a cluster and get redirected ui_created_window() is called on first connection. I'm looking into this issue.

**Comment by gilbsfr24** [comment]
no more call of ui_created_window since setup_user_requested_session_size implemented ...

**Comment by trentasis** [comment]
Hi @gilbsfr24 

Can you give details if in your environment with windows 2012r2 (multiple rdp servers) you are asked two time the password when you enter in the cluster?

I see that you connect using NLA, can you give details about rdesktop command used and what specific configuration you have made on widnwos server and linux client with rdesktop?

Thanks

**Comment by derfian** [comment]
I'm seeing the problem with the window not appearing when connecting to a Windows 2016 setup and rdesktop from git (da5153c). I ran `kinit` to get a kerberos ticket, and I am being redirected from the broker to a different server. Trying again after running `kdestroy` makes the window appear as expected.

The login sequence seems to stop after rdesktop has sent the Client Info PDU to the second server. The last lines of debug output before rdesktop stops are:
> Protocol(debug): rdp_send_logon_info(), sending RDP5-style Logon packet
> Protocol(debug): rdp_send_logon_info(), called sec_init with packetlen 364

**Comment by derfian** [comment]
I've also reproduced this problem with Windows 2012R2 servers with a recent build of rdesktop.

I have some indications that an older version of rdesktop (d124477abbc) still works, will try to verify & bisect this.

**Comment by derfian** [comment]
Bisecting points to commit b556651fe109c8802a0c798b8a680e5ff883bf4e being a source of problems.

**Comment by derfian** [comment]
> Bisecting points to commit b556651 being a source of problems.

I should clarify - I marked every revision that did not result in having a logged in rdesktop session after being redirected as bad. I'll do another run to find out where the Windows server stops responding to the client info PDU altogether.

**Comment by derfian** [comment]
Another bisect run where I marked all commits where the connection to the second server failed resulted in ab50ea31cf07483eb1b7d182d0768d2cde4a9f4f being marked as the first bad commit.

**Comment by derfian** [comment]
@gilbsfr24 , please test the latest changes on the master branch to see if rdesktop works for you now.

**Comment by gilbsfr24** [comment]
great job, it is working now
