### ISSUE TITLE
Hang when building with address sanitizer

### ISSUE THREAD

**Issue by paulmenzel** [rdesktop/rdesktop#230]
Building with the address sanitizer works, but the resulting binary doesn’t connect to the server, and times out

Tested configure options:

```
$ ./bootstrap
$ ./configure  --disable-credssp CFLAGS="-O0 -g -Wall -fsanitze=address"
[…]
$ ./rdesktop -d WIS-NET sommer
```

**Comment by uglym8** [comment]
On ArchLinux:

````
$ ./configure --disable-credssp CFLAGS="-O0 -g -Wall -fsanitze=address"
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/1/rdesktop':
configure: error: C compiler cannot create executables
See `config.log' for more details
````

But supplying configure option works as intended:
````
$ ./configure --disable-credssp --enable-address-sanitizer
````
I can connect to the TS without any issues (at least at the first glance).
The only difference is "-O2" (default opt level).
I even tried to set it to "-O0" and the got the same result.

What distro are you on?

**Comment by paulmenzel** [comment]
Very embarrassing, I wasn’t connected to the VPN. Sorry for the noise.

On that machine, I am using Ubuntu 17.10.
