### ISSUE TITLE
Issues with rdesktop & win2012r2

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#235]
Hi,

I have made test about two issues but I can't solve and I need some help about two issues:

1.- With previous versions you can log without to enter pwd from command line, since latest versions always is asked password from cmd and this is a problem for thinclients environments where is not showed to users, and this breaks compatibility, I think that is solved in https://github.com/rdesktop/rdesktop/pull/216

2.- This question is related with issue about authentication with windows 2012r2 cluster using connection broker, in any situation password is always asked 2 times, I have reaad multipled issues about this, but without any clear resolution and I'm not sure if this is solved or how to solve. Only using rdesktop server is reproduced. Anybody can give some information about how to use rdesktop without to ask always 2 times the password? what options or configuration I have to add to rdesktop?

additional information
https://github.com/rdesktop/rdesktop/issues/8
https://github.com/rdesktop/rdesktop/issues/228
https://github.com/rdesktop/rdesktop/issues/127

Thanks

**Comment by trentasis** [comment]
I have a question credssp is reuired or help to make login without to ask two times de password with rdesktop? IS this solved, how to configure this?
Thanks

**Comment by hean01-cendio** [comment]
The solution implemented on issue #127 solves the dual login prompts when connecting to a RDS cluster using rdesktop. If we merge #216 and you use that, you will not be able to login to a RDS cluster without providing passwords two times.

**Comment by trentasis** [comment]
Sorry but I'm newbie with rdesktop, I understand taht credssp is required to allows rds cluster login without ask two times password, right?
If this is correct what are the requirmenets, on OS and rdesktop parameters?

I'm in a loop, If I user -p then I can't use because is used without command interface, user only show grui from rdesktop, and with -p never can be entered pwd and never is executed... and then If I use merge 216 always I understand that password is asked two times...

Any suggestion how to implement a solution for both situations?

Thanks

**Comment by hean01-cendio** [comment]
> Sorry but I'm newbie with rdesktop, I understand taht credssp is required to allows rds cluster login
> without ask two times password, right?

No, you do not need CredSSP to solve the double cluster login. Basically, if you do not want login prompts you need to provide login credentials before connecting to the server. MSTSC does this and have for a few years and #127 implements this.

> Any suggestion how to implement a solution for both situations?

The reason of that #127 is not 100%, is that rdesktop does not provide a GUI and uses the console for prompting of a password. One can overcome this problem wrapping rdesktop into a script that launches a ask-pass application that then is provided into rdesktop via command line ```-p```, just like:

```
 /usr/libexec/openssh/gnome-ssh-askpass "RDP Remote password" | rdesktop -p - -u user -d DOMAIN server
```

**Comment by trentasis** [comment]
Hi @hean01-cendio 

Sorry but I'm not sure if this is valid for our environment, I'll try to give some details, we use rdesktop in thinclient, and always is executed without showing command line.

I understand i nthis example that that you suggest to install gnome-ssh-askpass to captures pwd and then reuse? It is valid for multiple user in same thinclient?

Are there any other option without to install gnome-ss-askpass?

Thanks

**Comment by trentasis** [comment]
my environment is a thicnlient, without gnome-ss-askpass, any other option
to solve this issue wiht double login in windows 2012r2, with windwos 2003
without any action was working ok, and would be very usefuel to thinclients
to keep this simple usage
Suggestions?

Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-25 9:35 GMT+01:00 Henrik Andersson <notifications@github.com>:

**Comment by derfian** [comment]
Hi @trentasis,

It doesn't have to be exactly gnome-ssh-askpass, it's just a convenient tool that does what we need it to, that also came pre-installed on systems we were working on at the time. If you don't have or don't trust gnome-ssh-askpass, @hean01-cendio wrote about other alternatives in [a guide on the rdesktop wiki](https://github.com/rdesktop/rdesktop/wiki/rdesktop-in-a-graphical-environment).

**Comment by trentasis** [comment]
Thanks for your information, I'll try to test and report the results!

**Comment by trentasis** [comment]
Thanks
