### ISSUE TITLE
Automatic reconnection not required when the session is requested on another client computer

### ISSUE THREAD

**Issue by gilbsfr24** [rdesktop/rdesktop#243]
My session is open on computer A.
I have to switch to another computer (computer B)
when connecting to the server, the session on computer A disconnects
I have my session OK
but I lost it because of the "reconnection process" of computer A
Do we have the reason to disconnect ... to avoid this?

**Comment by gilbsfr24** [comment]
maybe several reasons should not start a reconnection

https://msdn.microsoft.com/en-us/library/mt242409.aspx
ERRINFO_DISCONNECTED_BY_OTHERCONNECTION  : Another user connected to the server, forcing the disconnection of the current connection.

**Comment by derfian** [comment]
Could you try rdesktop from git? I tried to reproduce but the first rdesktop exited as expected with these messages in the log:

> Disconnecting...
> disconnect: The session was replaced.

**Comment by uglym8** [comment]
Close due to no response
