### ISSUE TITLE
some keys cannot be used

### ISSUE THREAD

**Issue by hlc926** [rdesktop/rdesktop#248]
I use the newest rdesktop to connect to  windows10,
keys( up、down、left、right、delete) cannot be used.

Version 1.8.3 do not have this problem.

**Comment by uglym8** [comment]
@hlc926, sorry for keeping you waiting.
You can't use these keys at all? 
Maybe you could specify the particular app that's failing?
TIA.

**Comment by hlc926** [comment]
@uglym8 , thank you.
Yes, I think It is all.  
I tried work, execl, file explorer, note, and can't used.

**Comment by uglym8** [comment]
Hmm.
 It's strange.
I couldn't reproduce this problem.
Everything works for me. 
Let's find out why your variant is failing:)


1. Do you have problems with numpad keys only or with arrow keys too?
2. Could you show the rdesktop output right after it's launched. This string looks like this
````
Autoselecting keyboard map 'en-us' from locale
````

**Comment by hlc926** [comment]
My keyboard is the "ThinkPad X1 Tablet Thin Keyboard".  Could be the reason?

It has the problems with the arrow keys and the "delete" key.

The output: 
Keyboard(error): xkeymap_read(), failed to open keymap en-us
Failed to initialize NLA, do you have correct Kerberos TGT initialized ?
Connection established using SSL.
Protocol(warning): process_pdu_logon(), Unhandled login infotype 1
Clipboard(error): xclip_handle_SelectionNotify(), unable to find a textual target to satisfy RDP clipboard text request

**Comment by uglym8** [comment]
Nope, I don't think the keyboard model is relevant to this issue. 

Aha, rdesktop fails to read keymap, that's why you've got problems with some keys.
````
Keyboard(error): xkeymap_read(), failed to open keymap en-us
````
1. How did you build the latest rdesktop?
2. Did you clone the repo i.e. git clone https://github.com/rdesktop/rdesktop.git?
3. From where do you run rdesktop?
If you run it from the clone then could you please make sure that there's keymaps/en-us in rdesktop dir?

**Comment by hlc926** [comment]
Aha, I got it.  I saw the xkeymap.c and found my problem. 
I fixed by " cp -a keymaps/* ~/.rdesktop/keymaps/ "

Thank you very much for your patience and help.

**Comment by uglym8** [comment]
Glad that it's has been resolved:)
Cheers.
