### ISSUE TITLE
redirection broken without iconv

### ISSUE THREAD

**Issue by mysec** [rdesktop/rdesktop#25]
If HAVE_ICONV is false or g_iconv_works isn't set, the following path ends up taken (rdp.c line 332 and 337):

`in_uint8a(s, &string[i++], 1);`
`...`
`                string[len] = 0;`

string is declared as char **, so this ... doesn't do what was intended.

GDB output of the resulting crash and a patch are attached.

[rdesktop-1.8.3-gdb.txt](https://github.com/rdesktop/rdesktop/files/112160/rdesktop-1.8.3-gdb.txt)
[rdesktop-1.8.3-redirfix.diff.txt](https://github.com/rdesktop/rdesktop/files/112163/rdesktop-1.8.3-redirfix.diff.txt)

**Comment by hean01-cendio** [comment]
Thanks for reporting this issue.
