### ISSUE TITLE
windows10's screen flashes problem

### ISSUE THREAD

**Issue by hlc926** [rdesktop/rdesktop#250]
Hello,
I use the newest rdesktop to connect to windows10.
Sometimes the screen flashes uninterruptedly. 
Like the pictures of the attachments.

![1986766566](https://user-images.githubusercontent.com/26218304/37515010-6a50c480-2901-11e8-8d28-4093c59f85b9.jpg)
![2058774464](https://user-images.githubusercontent.com/26218304/37515027-74e7f922-2901-11e8-9789-c8fa15b76d01.jpg)

Thank you and great job!

**Comment by derfian** [comment]
Hi @hlc926, thanks for the report.

Could you share the command line arguments you used with rdesktop to get this behavior? Looking for compression and similar settings.

**Comment by hlc926** [comment]
Hello @derfian ,
This is the command line, thank you.
`rdesktop -g 2160x1328@175 -u user -x lan -r clipboard:PRIMARYCLIPBOARD  -ppasswd ip &`

**Comment by hlc926** [comment]
It's not a problem of rdesktop.

**Comment by zzan1** [comment]
> It's not a problem of rdesktop.

How do you solved this problem?

**Comment by hlc926** [comment]
> > It's not a problem of rdesktop.
> 
> How do you solved this problem?

Use  XRender instead of OpenGL,  fedora29's :
`System Settings -> Hardware -> Display and Monitoring -> Mixer -> Rendering Diagram -> XRender`
