### ISSUE TITLE
Opened transaction after smart card authentication in windows

### ISSUE THREAD

**Issue by UndefBehavior** [rdesktop/rdesktop#257]
This bug was mentioned in your mailing list at the <a href="https://sourceforge.net/p/rdesktop/mailman/message/34321666/">sourceforge</a>. More than that, issuer provided a patch which fix it. 
I applied this patch on the current version of master and it works fine. Can you merge it please?

**Comment by uglym8** [comment]
Hi, thank you for your report.

This patch presumably fixes two issues:
1) Smartcard usage is blocked when rdesktop is connecting to the existing session which was previously authenticated via smartcard logon.

2) Filtering out smartcard reader hot plug.

> I applied this patch on the current version of master and it works fine. Can you merge it please?

Ok. 
Could you elaborate a little bit?
How did you test that it works?
I'd be very grateful if you could specify how I can reproduce the problem (1).

Regarding problem (2): 
I'll see to it while fixing #239 as I definitely can see new readers insertion events.
I'll additionally  write simple app to test whether client receives the notification for new  reader arrival
as in #239 I describe the behaviour of closed sourced application.

Best regards.

**Comment by UndefBehavior** [comment]
We faced the first issue. There is the test case:
1. Redirect the smartcard with the certificate for logon via rdesktop.
2. Use smartcard logon for authentication in Windows.
3. Try to request new certificate via MMC on redirected smartcard.

Expected behavior:
New certificated was requested.

Current behavior:
MMC freezes after selecting Certificate Enrollment Policy.

This issue takes place because of the opened transaction after smartcard logon. If you get a debug information via `RDESKTOP_DEBUG=SmartCard` from the smartcard logon process, you will see that there are more SCardBeginTransaction functions than SCardEndTransaction functions. Microsoft Base Smart Card Crypto Provider layer is used for communication with a smartcard.
You can see my log in the attachment.
[log rdesktop minidrv.txt](https://github.com/rdesktop/rdesktop/files/1871060/log.rdesktop.minidrv.txt)

**Comment by uglym8** [comment]
@rkondratenko, thank you for your contribution.
@UndefBehavior, thank you again for your testing.

I've just made the PR #258  with a fix to issue (1).

Could you please check issue (2) as well if, of course, you've got a spare time?
Try to connect to Windows host without Rutoken inserted and later (while at logon screen) try to insert it.

Is Windows able to see this token without this patch?
If you apply this patch does the Windows behaviour change?

**Comment by UndefBehavior** [comment]
I checked issue(2) with two cases:

1st test case:
1) Connect to Windows host without any token inserted with `-r scard` option;
2) Insert Rutoken in my machine.
Before/after patch: Windows don't see inserted token on logon page.

2nd test case:
1) Connect to Windows host with Rutoken inserted with `-r scard` option;
Before/after patch: Windows sees inserted token on logon page.
2) Disconnect Rutoken;
Before/after patch: Windows don't see any token on logon page.
3) Reconnect Rutoken;
Before patch: Windows don't see reconnected token on logon page.
After patch: Windows sees reconnected token on logon page.

My pcsc-lite version is 1.8.23

**Comment by uglym8** [comment]
@UndefBehavior, thank you for thorough testing.

I'm a little bit worried about the 1st test case's clause 2 behaviour:

>2. Insert Rutoken in my machine.
Before/after patch: Windows don't see inserted token on logon page.

My guess that it should work the same way as in 
> Reconnect Rutoken;
Before patch: Windows don't see reconnected token on logon page.
After patch: Windows sees reconnected token on logon page.

Could you check whether Windows Remote Desktop client (MSTSC.EXE) works the same way?

If you don't have a windows box to use as a client for testing, it's okay, I'll test myself a little bit later (I've got  Rutokens, but don't have Windows servers setup for smart card authentication).

Meanwhile, I'll check the scard status handling.

**Comment by UndefBehavior** [comment]
Unfortunately, I couldn't test it via MSTSC but I figured out where the problem could be. PnP notification works fine if you have some tokens inserted at the start of rdesktop, but doesn't work at all if there are no tokens at the start. Judging by pcsc log, rdesktop calls SCardGetStatusChange for all inserted tokens and virtual PnP reader only if it has found any tokens on SCardListReaders call earlier. If SCardListReaders was not successful (no readers), SCardGetStatusChange is never called (same behavior can be found in xfreerdp), which leads to not working PnP notification. If you know where this logic could be implemented, we should fix this by handling special situation when no tokens were found.

**Comment by uglym8** [comment]
Okay.
I think we're capable to fix it together really quick thanks to your hints about SCardListReaders() call.

Could you please apply this patch (https://gist.github.com/uglym8/f78e9e55dc64c9b2c83133fccbce2d0f) and test this issue again?

TIA.

**Comment by UndefBehavior** [comment]
I edited your patch and it is working fine now. I'm unsure about logic of this change. Can you tell me how rdesktop handles PnP notification? I couldn't locate it myself (except for excluding reader with that name from SCardGetStatusChange sometimes).
<a href="https://gist.github.com/UndefBehavior/45f06a2a2f3e789d224502915e302364">Modded patch</a>

**Comment by uglym8** [comment]
Btw, why do you need to add 
rv = SCARD_S_SUCCESS; in a case of SCARD_E_NO_READERS_AVAILABLE?

Does Windows experience the same problem without this change?

As it seems to me this is not 100%  correct approach.
I guess we should return SCARD_E_NO_READERS_AVAILABLE and later detect new reader (as Windows should ask us about "\\?PnP?\Notification".) and report it back.
We've already added support for PnP notification in the second part of the original part.

**Comment by UndefBehavior** [comment]
I modded your patch because it didn't work properly without it (SCardEstablishContext shouldn't <a href="https://pcsclite.alioth.debian.org/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67">return</a> SCARD_E_NO_READERS_AVAILABLE. Seems that it is important for Windows).
I figured out PnP notification's place now, ty. I already tested it on patches from sourceforge + yours + mine.

**Comment by uglym8** [comment]
Could you please test PR #258 (https://github.com/uglym8/rdesktop/tree/sc_drop_refs) and verify that it works correctly in your case.
TIA.

**Comment by UndefBehavior** [comment]
I tested it and I can verify that all is OK)
