### ISSUE TITLE
Build for Windows 10

### ISSUE THREAD

**Issue by danelsan** [rdesktop/rdesktop#260]
There are istruction for building the source code
with crossplatform? Thanks

I try  

./configure --host=i686-w64-mingw32

But result is:

checking build system type... x86_64-unknown-linux-gnu
checking host system type... i686-w64-mingw32
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for X... no

ERROR: Could not find X Window System headers/libraries.
Probably you need to install the libx11-dev package.
To specify paths manually, use the options --x-includes and --x-libraries.

**Comment by hean01-cendio** [comment]
I guess you have found build instructions for cross compiling Seamless RDP binaries for windows.

rdesktop can not be built as Windows binary.

**Comment by Leafire12** [comment]
I have version 1.7.0 compiled for windows with this tutorial:
http://www.soren.schimkat.dk/Blog/?p=69

**Comment by hean01-cendio** [comment]
> rdesktop can not be built as Windows binary.

I take that one back, never knew about Xming :)
