### ISSUE TITLE
current builds seem to be assuming/forcing the "-p -" option when not specified, and core dumps when unable to read from stdin

### ISSUE THREAD

**Issue by Rakasa** [rdesktop/rdesktop#262]
current builds seem to be assuming/forcing the "-p -" option when not specified, and core dumps when unable to read from stdin

Originally discovered as a side effect of investigating [issue #251](https://github.com/rdesktop/rdesktop/issues/251), this issue has been confirmed to be present in the current master as well.

Environment for testing is Fedora 27, updated to "current" as of a week or so ago.  Issue is not present in the old build that comes stock with Fedora.  Using the current master or the test build from issue #251 has this issue.  rdesktop is called from a script using the following parameters:

```
rdesktop -g 1910x1130 -r clipboard:PRIMARYCLIPBOARD -u $USERNAME -z -a 24 -T "${server}_connection" -P -r sound:local  ${server} >>/tmp/rdesktop_${server}_`date +%Y-%m-%d_%H.%M.%S_%Z`.log 2>&1 &
```

core dump is near instant in reproducing.  error message (below) indicates it is looking for the password to be provided on stdin even though the "-p -" option was not specified:
```
Core(error): Failed to read password or pin from stdin
```
-- Rakasa

**Comment by uglym8** [comment]
Yes, the password is mandatory now.
Please check #191 for the couple of hints of how to launch rdesktop from scripts or via shortcuts.

**Comment by Rakasa** [comment]
That entirely breaks usability in my environment for some of my servers which use a 2fa that provides a challenge PIN to be entered on the mobile device and the response PIN comes from the device after the challenge PIN is provided.  A failed entry terminates the connection immediately, and providing an obviously wrong PIN on the cli or stdin counts as a failure, terminating the connection before I even see the challenge PIN.

If changing this is not to be considered, I have no choice but to stay on the old build that still works correctly.  (At present I do not have confidence in my ability to isolate and revert this change myself).

-- Rakasa

**Comment by Rakasa** [comment]
I also consider coring when no password is provided and the "-p" option is not specified to be a bug; at most it should be a usage message noting that "-p" is considered required by the current build.

Changes to RDS behavior at most should result in rdesktop exiting cleanly with a message stating that the server being connected to is requiring the password to be supplied to initiate the connection, and that message should only come up if the remote server truly is -- not based on any assumptions.  This behavior is explicitly disabled in many environment intentionally.

-- Rakasa

**Comment by uglym8** [comment]
I don't think that rdesktop core dumps in this case.
It merely informs about the problem and "**Core**" in this particular case is just an indication that this error is related to core part of the protocol.

I agree with you that in your case (i.e. 2fa) it's really inconvenient that your're required to provide password before connecting.
I'll check again #191 and propose the solution.

**Comment by Rakasa** [comment]
Rereading the comments on #191 a few times, I have to logically agree that forcing the password from the cli at all times was a step backwards and adding another separate option to allow not specifying a password on top of that would be another step backwards.

Rather than adding the additional, effectively redundant, option to explicitly say "no password provided from cli, connect anyway" (this is logically implied by omission of the '-p' option), I think the much more logical step would be reverting the change to require a password from the cli in the first place.  If the remote server does in fact require the password at initial connection, a clean program exit with a message stating "remote server requires password to be provided for initial connection".  (I did look more closely at the code, and you're correct, it is not coring, that was my misinterpretation of the failure message).

The 'password at initial connection' is a change to RDS behavior that is not universal, and even in Windows 2016, this can be disabled.  My environments that provide the challenge PIN after initial connection are Windows 2016 servers.  (I've no idea what package is installed for the challenge/response PIN; I do not control these servers myself).

-- Rakasa

ps:  I think "inconvenient" is an understatement when this change (and not knowing about it) caused my account to be locked out for too many failed attempts...  for these hosts I am forced to use the antiquated version that comes with Fedora as it is entirely impossible to log in with any version that requires the password to be provided on the cli.  ;)

**Comment by Rakasa** [comment]
I don't know enough about the redirection to intelligently comment other than I've never encountered it that I'm aware of, and until now have always used the old rdesktop build that came with the distro I was using.  Based on the information in the redirection tickets, I'd venture the old build doesn't work with redirection, so I've simply never come across it myself.

At the same time, remote server requiring a password and redirection failing without the password already being supplied on the cli seems to me to be a doc/usage issue rather than a fault of rdesktop not requiring the password on the command line by default.

Is redirection something rdesktop can detect and then inform the user about "-p" being required because the remote server is using redirection (or otherwise requiring it)?  Much as I greatly prefer straight forward logic regarding cli options and their omission/inclusion, without a way to detect the password being required for whatever reason, I... I don't like the redundancy involved in an additional option to be able to return to the previous operation when it is needed, but I can't argue in favor of breaking things like the redirection support if we can't detect the redirection and notify the user of its caveats.

-- Rakasa

**Comment by hean01-cendio** [comment]
Commit bc727e7 adds the ability to provide an empty password that will make rdesktop not to ask for password and take the user to the remove logon screen.

@Rakasa this should solve your issues with two factor authentication.

**Comment by Rakasa** [comment]
@hean01-cendio implemented as 
`-p ""`
on the command line?

~ Rakasa

**Comment by hean01-cendio** [comment]
@rakasa, yes, just like so

**Comment by Rakasa** [comment]
Confirmed working, thank you  :)

~ Rakasa
