### ISSUE TITLE
Compilation errors with 1.8.3

### ISSUE THREAD

**Issue by korolmi** [rdesktop/rdesktop#268]
Hello,

ubuntu 18.04 64 bit
./configure --disable-smartcard
make
got errors in ssl.c:

ssl.c: In function ‘rdssl_cert_to_rkey’:
ssl.c:149:24: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                        ^~
In file included from ssl.h:27:0,
                 from ssl.c:22:
ssl.c: In function ‘rdssl_rkey_get_exp_mod’:
ssl.c:204:24: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
  if ((BN_num_bytes(rkey->e) > (int) max_exp_len) ||
                        ^
ssl.c: In function ‘rdssl_hmac_md5’:
ssl.c:232:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;
           ^~~
ssl.c:233:2: warning: implicit declaration of function ‘HMAC_CTX_init’; did you mean ‘HMAC_CTX_new’? [-Wimplicit-function-declaration]
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
  HMAC_CTX_new
ssl.c:235:2: warning: implicit declaration of function ‘HMAC_CTX_cleanup’; did you mean ‘HMAC_CTX_get_md’? [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
  HMAC_CTX_get_md
ssl.c:232:11: warning: unused variable ‘ctx’ [-Wunused-variable]
  HMAC_CTX ctx;
           ^~~
Makefile:161: recipe for target 'ssl.o' failed

**Comment by uglym8** [comment]
Hi,
please check #215

**Comment by uglym8** [comment]
Closed due to no response.
