### ISSUE TITLE
ERROR: CredSSP: Initialize failed,

### ISSUE THREAD

**Issue by omps** [rdesktop/rdesktop#28]
The issue still seems to persist, I am using rdesktop version 1.8.3, and checked on many forums, the issue seems to have gone with newer version, but for me the issue still looks the same.
```
[~ (master)]$ rdesktop -u omps localhost -PKD -fz -p -
Autoselected keyboard map en-us
Password: 
ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?
Connection established using SSL.
ERROR: SSL_write: 1 (Success)
```

**Comment by omps** [comment]
tried downloading and configuring from the latest source issue remains the same

https://github.com/rdesktop/rdesktop.git
```
[~ (master)]$ /usr/local/bin/rdesktop -u user localhost -PKD -fz -p -
Autoselected keyboard map en-us
Password: 
ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?
ERROR: recv: Connection reset by peer

[~ (master)]$ /usr/local/bin/rdesktop
rdesktop: A Remote Desktop Protocol client.
Version 1.8.3. Copyright (C) 1999-2011 Matthew Chapman et al.
See http://www.rdesktop.org/ for more information.

```

**Comment by omps** [comment]
The issue is resolved,

downloaded and Compiled the source pacakge again with the following arguments.

 ```./configure --prefix=/opt --disable-smartcard --disable-credssp```

**Comment by hean01-cendio** [comment]
HI, out of curiosity, which RDP desktop service are you trying to connect to ?

**Comment by omps** [comment]
windows...

**Comment by flip111** [comment]
I still get this error, don't know what it means either

```
» ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?
Connection established using SSL.
```

**Comment by hean01-cendio** [comment]
More info on this topic is found on issue #71

**Comment by mayanksuman** [comment]
Though it is closed, I have got a solution to this issue. 

On windows machine in system settings -- go to remote -- and select the option "Allow computer to connect running any version of remote desktop"

**Comment by hean01-cendio** [comment]
Turning on "Allow computer to connect running any version of remote desktop" will disable Network Level Authentication eg. NLA which decreasing security. For further input on the issue, see issue #71

**Comment by nu11secur1ty** [comment]
Dear 'mayanksuman' this is not a solution. :D

**Comment by lszyba1** [comment]
https://github.com/rdesktop/rdesktop/issues/72

**Comment by lszyba1** [comment]
https://github.com/FreeRDP/Remmina/issues/1513
March 13th 2018 Windows updates kill Reminna RDP

**Comment by hean01-cendio** [comment]
Wiki page added with information about CredSSP

https://github.com/rdesktop/rdesktop/wiki/Network-Level-Authentication-(NLA)

**Comment by froque** [comment]
remmina project moved to gitlab. the bug url is now: https://gitlab.com/Remmina/Remmina/issues/1513

**Comment by marcosribeiro15** [comment]
join with dns name and inside the domain maybe work.
