### ISSUE TITLE
Missing Error Check in function BN_bin2bn()

### ISSUE THREAD

**Issue by lc3412** [rdesktop/rdesktop#280]
Function BN_bin2bn() returns returns the BIGNUM, otherwise NULL on error. However , the return value of function BN_bin2bn() is not checked. See the following code:

line: 125,126,127
https://github.com/rdesktop/rdesktop/blob/74b2129e09ee753f952132d317afe5b503fec07e/ssl.c#L105-L139

===================================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/crypto folder

Ref: https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/crypto/srp/srp_vfy.c#L236-L238

```c
line 236:    vinfo->s = BN_bin2bn(tmp, len, NULL);
line 237:    if (vinfo->s == NULL)
line 238:        goto err;
```

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by uglym8** [comment]
Hi!

Thank you for your time.

While you're right about the issue I do hope that we'll merge #137 which will render this error absolete.

Best regards.

**Comment by hean01-cendio** [comment]
We have now moved to GnuTLS
