### ISSUE TITLE
Missing Error Check in function BN_mod_exp()

### ISSUE THREAD

**Issue by lc3412** [rdesktop/rdesktop#281]
Function BN_mod_exp() returns 1 for success, 0 on error. The return value should always be checked. However , the return value of function BN_mod_exp() is not checked. See the following code:

line: 128
https://github.com/rdesktop/rdesktop/blob/74b2129e09ee753f952132d317afe5b503fec07e/ssl.c#L105-L139

=================================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/crypto folder

Ref: https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/crypto/bn/bn_blind.c#L294-L295

```c
line 294:  if (!BN_mod_exp(ret->A, ret->A, ret->e, ret->mod, ctx))
line 295:      goto err;
```

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by uglym8** [comment]
Hi!

Thank you for your time.

While you're right about the issue I do hope that we'll merge #137 which will render this error absolete.

Best regards.

**Comment by hean01-cendio** [comment]
We have replaced OpenSSL with GnuTLS which renders this issue invalid.
