### ISSUE TITLE
rdesktop not grabbing keyboard shortcuts

### ISSUE THREAD

**Issue by metmayhem** [rdesktop/rdesktop#283]
When I'm connected to a remote session and try to perform alt+tab or anything other key combination it doesn't perform the shortcut on the remote machine, but instead on the local one. The window has focus, and is happens whether I'm in fullscreen or not. I can type in the remote session just fine, and if the shortcut is only recognized by my remote machine (i.e. there is no mapping for it on my host machine), then the shortcut works fine.

**Comment by uglym8** [comment]
Hi!

Thank you for your report.

Just checked it using the latest source from master and  1.8.2post.
The only way I could get the same behaviour as yours was the time when rdesktop window has focus but mouse pointer was out of this window.
Could not get this behaviour with fullscreen though.
Could you please provide a little bit more details (rdesktop version, Linux distribution, desktop environment).
TIA.
Best regards.

**Comment by metmayhem** [comment]
I figured it out. It ended up being a Wayland issue. I switched to a different manager and it works now.

**Comment by uglym8** [comment]
Good.
Closing as resolved then.
Best regards.
