### ISSUE TITLE
Shared Printer TS Port Issue

### ISSUE THREAD

**Issue by vdite** [rdesktop/rdesktop#29]
If i am starting redesktop with

rdesktop -f -r printer:ql570 iu user -z -g 1024x768 HOSTIP

every starting TS-Ports are counting plus.
This start, the shared XUBUNTU Printer Port is TS065
Next start, the shared XUBUNTU Printer Port is TS066
....
...
Next start, the shared XUBUNTU Printer Port is TS166
and so on... so i have always to switch the port for printing.
##

**Comment by hean01-cendio** [comment]
> Next start, the shared XUBUNTU Printer Port is TS166
> and so on... so i have always to switch the port for printing.

Do you actually mean that you do not want the redirected printer to be default printer to be used within the session ?

or

That there is a problem to use the default redirected printer when you connect/reconnect to a session ?

**Comment by hean01-cendio** [comment]
Closing due to no response.
