### ISSUE TITLE
password login page cannot be used normally on Windows Server 2003 as terminal server

### ISSUE THREAD

**Issue by erikhydro** [rdesktop/rdesktop#300]
We are using Windows Server 2003 as a terminal server. We connect to it via rdesktop. Users are used to getting the standard windows logon screen where they enter domain,user and password. it is prefilled with user by using the -u option. it is also prefilled with domain by using the -d option. But then the user has to enter the password in the password field.

But now with the current version in the master branch there is always a password prompt on the commandline. Of course there is no commandline when starting rdesktop from a gui. The only workaround is to use -p xxx and then see the "wrong password" message box. The user then has to enter the correct password. But that is obviously ugly.

What I did is comment out this complete block of code in rdesktop.c:

```C
/* If no password provided at this point, prompt for password / pin */
if (!g_password[0])
{
	if (read_password(g_password, sizeof(g_password)))
	{
		flags |= RDP_INFO_AUTOLOGON;
	}
	else
	{
		logger(Core, Error, "Failed to read password or pin from stdin");
		return EX_OSERR;
	}
}
```

And then rdesktop is working again, since the option RDP_INFO_AUTOLOGON gets not set. Examinating the code I find no other way to make sure RDP_INFO_AUTOLOGON gets not set. This option is simply always set.

I found some other issues here regarding the no password prompt issue, but there it is talked about RDP redirecting which I don't even know that it exists :-) For that reason I opened a new issue to point out that there is a very simple argument for having a no password option:

*With old versions I was able to connect to windows 2003 terminal server using its native password prompt. This is not possible anymore.*

**Comment by uglym8** [comment]
Hi, 

Thank you for your report.
Sorry for inconvenience this feature caused you.

We have other reports regarding this matter as well (as you've probably already found out).

I think that will finally decide how to deal with it in the nearest future.

Take care.

**Comment by hean01-cendio** [comment]
Commit bc727e7 add the option to provide a empty password to disable password prompt and take the user to remote login form.
