### ISSUE TITLE
rdesktop 1.8.4 doesn't build against libressl 2.6

### ISSUE THREAD

**Issue by jo77ah** [rdesktop/rdesktop#308]
bd6aa6a introduces a guard for RSA_get0_key. this guard doesn't work for libressl, since it sets the version number to 0x20000...
to fix this you need to test `defined(LIBRESSL_VERSION_NUMBER)`.

I'm not sure, if this is relevant for a bug fix release. But it will most certainly be irrelevant for 1.9, if #298 lands.

There is a patch available in gentoo: https://664202.bugs.gentoo.org/attachment.cgi?id=563060

**Comment by hean01-cendio** [comment]
@jo77ah I'm working on the last parts of GnuTLS to get it included in rdesktop 1.9.0.

**Comment by hean01-cendio** [comment]
Closing this issue due to rdesktop is now using GnuTLS.
