### ISSUE TITLE
Seamless RDP support for Window 10 Pro October Update

### ISSUE THREAD

**Issue by cytrinox** [rdesktop/rdesktop#312]
SeamlessRDP provided by https://www.cendio.com/seamlessrdp is well known and provides support for Windows Server products. It is also well known that it only work on Windows Server editions.

I have discovered another tool from Kim Knight called **RemoteAppTool**, which provides a simple tool to create RDP files for Seamless RDP connections: https://sites.google.com/site/kimknight/remoteapptool

RemoteAppTool has Support for Windows 10 Enterprise, Ultimate etc., but not for Windows 10 Professional.
But this has changed since the Windows 10 October Update. Microsoft has integrated some RDP services which allows Seamless RDP to work.

I have tested RemoteAppTool on my Windows 10 Professional with October Update. I can sucessfully build a RDP file for notepad.exe and connect to it seamless from another Windows machine.

Is there any chance to get this working with *rdesktop* from Linux? I've installed Cendio's seamlessrdp and called it with *-A* parameter without luck. I'm not sure if Windows 10 Oct. Update now provides a possible replacement of seamlessrdp (as in makes seamlessrdp deprecated in the future). Maybe I need to specifiy some binary as -A argument which is now included in Windows?

**Comment by CendioOssman** [comment]
I don't think the new update will have any effect on SeamlessRDP. RemoteApp is Microsofts version of SeamlessRDP. They don't really share any technical parts though, and rdesktop currently has no support for RemoteApp.

The only change might be if Windows 10 previously did not allow running the SeamlessRDP shell, and that is now possible. Follow the instructions on the Cendio page and it should be fine in that case. Also note that you usually cannnot be logged on locally for SeamlessRDP to work on a workstation version of Windows.

And yes, a path to the SeamlessRDP shell is required as an argument to -A.

**Comment by cytrinox** [comment]
Thanks for the clarification of the differences between RemoteApp and SeamlessRDP.

> Also note that you usually cannnot be logged on locally for SeamlessRDP to work on a workstation version of Windows.

This sounds like it would be possible to use seamlessrdp on Windows 10? I was not logged on locally, I've just started *rdesktop -A "%ProgramFiles%\ThinLinc\WTSTools\seamlessrdpshell.exe" -s "C:\Windows\system32\notepad.exe"* but it always starts a full remote session. As the website states that it would not work on Windows 10 I've not done any debugging/log checking. But if it should work, I'll have a deeper look.

**Comment by CendioOssman** [comment]
That usually happens because a default Windows machine doesn't allow running custom commands. So you need to enable that feature, and permit "seamlessrdpshell.exe" to be used as a command. Confusingly, these settings are usually grouped under the RemoteApp banner. They are used for more than RemoteApp though.
