### ISSUE TITLE
cloned 2019-02-12, `./configure` reports libtasn1 missing when already installed on Fedora 29

### ISSUE THREAD

**Issue by Rakasa** [rdesktop/rdesktop#315]
What version of libtasn1 is needed?

running ./configure, I get:
`rdesktop requires libtasn1. Please install the dependency`

However, trying to install the library, I get
`$ sudo dnf install libtasn1`
`Last metadata expiration check: 0:00:31 ago on Tue 12 Feb 2019 09:29:18 AM EST.`
`Package libtasn1-4.13-5.fc29.x86_64 is already installed.`
`Package libtasn1-4.13-5.fc29.i686 is already installed.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

~ Rakasa

**Comment by uglym8** [comment]
Please try installing libtasn1-devel package

**Comment by Rakasa** [comment]
That resolved it.  Is it expected that all of the reported failed dependencies will actually be for the -devel counterpart package?

~ Rakasa

**Comment by CendioOssman** [comment]
Yes. The "normal" package only include the stuff needed to run programs. The -devel packages are needed to be able to build new programs.

**Comment by glennmichaelmejias** [comment]
@uglym8 you tell us to install libtasn1-devel package but you dont tell us how to install it. how to install it? thanks.
