### ISSUE TITLE
Connections with virtualbox broken again

### ISSUE THREAD

**Issue by lgommans** [rdesktop/rdesktop#319]
`rdesktop` and `rdesktop-vrdp` as included in the Debian repositories, 1.8.4, cannot connect to the VirtualBox remote viewer. Last October I built this repository from sources and that works. Now I updated with `git pull`, rebuilt it, and it broke again.

With the most recent commit to master:

    $ ./rdesktop -v -x 1440x900 192.168.1.2
    Autoselecting keyboard map 'en-us' from locale
    Password: 
    is_wm_active(): WM name: Mutt
    Connecting to server using SSL...
    Protocol(warning): Protocol negotiation failed with reason: no valid authentication certificate on server
    Retrying with plain RDP.
    Core(error): rcp_recv(), connection closed by peer

The known working version:

    $ git checkout ca03f60
    $ ./bootstrap
    $ make
    $ ./configure --disable-smartcard
    $ make
    [it only builds correctly the second time after a configure run]
    $ ./rdesktop -v -x 1440x900 192.168.1.2
    Autoselecting keyboard map 'en-us' from locale
    Password: 
    Connecting to server using SSL...
    Protocol(warning): Protocol negotiation failed with reason: no valid authentication certificate on server
    Retrying with plain RDP.
    Disabling dynamic session resize
    Connection successful

Doing a brief bisection search / binary search to narrow down when the regression was introduced, it was between commits 166d1bc14d34c20dd0c640571a749a6599180367 (the last working version) and 90fd660803282713c3e2d29207dc26255f2e3899 (the next commit, broken).

The virtualbox version:

    $ vboxmanage --version
    5.2.26r128414

Hope this helps!

**Comment by CendioOssman** [comment]
Hmm... Not obvious how that commit broke things.

Could you run things with `RDESKTOP_DEBUG=All` so we see a bit better where it fails? And have you checked the logs from VirtualBox.

Is is possible to get VirtualBox to use TLS? The legacy mode is not something we put much effort in to as Microsoft's servers no longer use it.

**Comment by lucb1e** [comment]
I did not know about that envvar! Trying with the latest version from `master`:

    $ RDESKTOP_DEBUG=All ./rdesktop -v -x 1440x900 127.0.0.1
    Autoselecting keyboard map 'en-us' from locale
    Password: 
    UI(debug): RDP depth: 24, display depth: 24, display bpp: 32, X server BE: 0, host BE: 0
    
    Keyboard(debug): add_to_keymap(), adding translation, keysym=0xffe2, scancode=0x36, modifiers=0x0
    [loads of other add_to_keymap() messages]
    Keyboard(debug): xkeymap_read(), Keylayout 0x409
    Keyboard(debug): add_to_keymap(), adding translation, keysym=0x21, scancode=0x2, modifiers=0x2
    [...]
    Keyboard(debug): add_sequence(), adding sequence for keysym 'ntilde' (0xf1)
    Keyboard(debug): add_sequence(), adding sequence for keysym 'Ntilde' (0xd1)
    [loads more add_to_keymap and add_sequence messages]
    Keyboard(debug): add_to_keymap(), adding translation, keysym=0x3f, scancode=0x35, modifiers=0x2
    is_wm_active(): WM name: Mutt
    Core(debug): dvc_channels_add(), Added hash=67f73722, channel_id=-1, name=Microsoft::Windows::RDS::DisplayControl, handler=0x563d6d072ca0
    Protocol(debug): rdp_reset_state()
    Protocol(debug): mcs_connect_start()
    Connecting to server using SSL...
    Core(debug): tcp_connect(), trying 127.0.0.1 (127.0.0.1)
    Protocol(warning): Protocol negotiation failed with reason: no valid authentication certificate on server
    Retrying with plain RDP.
    Core(debug): tcp_connect(), trying 127.0.0.1 (127.0.0.1)
    Protocol(debug): sec_out_mcs_connect_initial_pdu()
    Protocol(debug): sec_out_mcs_data(), g_num_channels is 5
    Protocol(debug): sec_out_mcs_data(), requesting channel cliprdr
    Protocol(debug): sec_out_mcs_data(), requesting channel rdpsnd
    Protocol(debug): sec_out_mcs_data(), requesting channel snddbg
    Protocol(debug): sec_out_mcs_data(), requesting channel rdpdr
    Protocol(debug): sec_out_mcs_data(), requesting channel drdynvc
    Protocol(debug): mcs_connect_finalize()
    Protocol(debug): mcs_send_connect_initial()
    Protocol(debug): mcs_recv_connect_response()
    Protocol(debug): sec_process_mcs_data()
    Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_INFO
    Protocol(debug): sec_process_srv_info(), server RDP version is 4
    Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_CHANNELS
    Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_CRYPT
    Protocol(debug): sec_process_crypt_info()
    Protocol(debug): sec_parse_crypt_info()
    Protocol(debug): sec_parse_crypt_info(), We're going for the RDP4-style encryption
    Protocol(debug): sec_parse_crypt_info(), got public key
    Protocol(debug): sec_parse_crypt_info(), generating client random
    Protocol(debug): sec_generate_key(), rc_4_key_size == 2, 128-bit encryption enabled
    Protocol(debug): mcs_send_edrq()
    Protocol(debug): mcs_send_aurq()
    Protocol(debug): mcs_recv_aucf()
    Protocol(debug): mcs_send_cjrq(), chanid=1002
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1003
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1004
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1005
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1006
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1007
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): mcs_send_cjrq(), chanid=1008
    Protocol(debug): mcs_recv_cjcf()
    Protocol(debug): rdp_send_logon_info(), sending RDP5-style Logon packet
    Protocol(debug): rdp_send_logon_info(), called sec_init with packetlen 348
    Core(error): rcp_recv(), connection closed by peer

VirtualBox should support TLS, but I couldn't easily get it to work. Since I don't trust the service enough to expose it to the Internet anyway, I'll access it via ssh tunneling, so I didn't bother figuring the TLS setup out. If plain RDP is no longer supported (which I'd totally understand, it's like supporting telnet), then let's close this issue, I'll just stick with the old rdesktop version, and if I ever setup TLS I can open a new issue for any issues :). In that case, though, it might be nice to put a small note for vbox users somewhere that they should use commit ID abcdef and be aware of the risk of plain rdp.

**Comment by CendioOssman** [comment]
Unfortunately that log didn't really reveal much more. It seems the server is getting upset about something. So the next step would be to try to get debugging info out of VirtualBox.

We haven't formally deprecated plain RDP yet. But issues with it will not be on the top of our list since extremely few users still use it. :)

**Comment by lgommans** [comment]
> the next step would be to try to get debugging info out of VirtualBox.

Err, I should have thought of that myself :-)

```
165:33:15.780996 VRDP: New connection: 
165:33:15.781102 VRDP: Connection opened (IPv4): 10
165:33:15.781810 VRDP: Negotiating security method with the client.
165:33:15.782892 VRDP: failed to access the server certificate file: /root/vbox-rdp.crt
165:33:15.782989 VRDP: Connection closed: 10
165:33:15.907871 VRDP: New connection: 
165:33:15.907988 VRDP: Connection opened (IPv4): 11
165:33:15.908780 VRDP: Negotiating security method with the client.
165:33:15.961450 VRDP: Methods 0x00000003
165:33:15.961483 VRDP: Channel: [cliprdr] [1004]. Accepted.
165:33:15.961494 VRDP: Channel: [rdpsnd] [1005]. Accepted.
165:33:15.961504 VRDP: Channel: [snddbg] [1006]. Not supported.
165:33:15.961514 VRDP: Channel: [rdpdr] [1007]. Accepted.
165:33:15.961526 VRDP: Channel: [drdynvc] [1008]. Accepted.
165:33:16.342513 VRDP: Failed to process incoming RDP packet: VERR_VRDP_SEC_ENGINE_FAIL!!!
165:33:16.342513 VRDP: The RDP packet content (read):
165:33:16.342513 
165:33:16.342513 00007f44e8028318 0000: 03 00 00 5f 02 f0 80 64-00 01 03 eb 70 80 50 01 ..._...d....p.P.
165:33:16.342513 00007f44e8028328 0010: 00 00 00 48 00 00 00 7f-d1 6f c8 cd ec bb 9d 0a ...H.....o......
165:33:16.342513 00007f44e8028338 0020: a1 b2 91 e5 40 c5 ef 11-b3 c5 6b 7a 4b 54 51 80 ....@.....kzKTQ.
165:33:16.342513 00007f44e8028348 0030: 00 14 c5 a6 68 b3 06 34-ae 44 97 21 97 37 d4 66 ....h..4.D.!.7.f
165:33:16.342513 00007f44e8028358 0040: 1b 96 68 e4 ea 14 ff e5-10 04 fb 60 f3 63 d6 e4 ..h........`.c..
165:33:16.342513 00007f44e8028368 0050: 48 99 09 03 fe a2 55 00-00 00 00 00 00 00 00    H.....U........
165:33:16.342513 
165:33:16.342513 VRDP: Connection closed: 11
```

Note that I entered the wrong password on purpose to prevent a hashed variant leaking in that hexdump. The error looks the same with the correct password.

I suppose that error log also hints at what the TLS issue might be ^^'. Nevertheless, might be good to fix this bug as well, if it's not a lot of work.

Does this help? Is there anything else I could try or provide?

**Comment by CendioOssman** [comment]
This should help, yes. Unfortunately I cannot look at it right now. What would need to be done is to compare that package with Microsoft's protocol documentation and see where something deviates.

Or if everything is ok, report to VirtualBox that they have some issue in their protocol parser.

**Comment by Mno-hime** [comment]
Providing fresh debug logs from VirtualBox 6.0.8 and rdesktop 1.8.99 (6028c999ba7852d560b7831853502e675c65709a):

[oi-minimal-2019-07-29-10-35-20.log](https://github.com/rdesktop/rdesktop/files/3441085/oi-minimal-2019-07-29-10-35-20.log)
[rdesktop.log](https://github.com/rdesktop/rdesktop/files/3441086/rdesktop.log)

**Comment by btaroli** [comment]
While it's understandable this might not be the highest priority, there are still a lot of people who use VirtualBox. And this seems to affect even the latest releases. If there is a better more compatible way to configure VRDP/VRDE for use with rdesktop, that would survive the march forward, what would that be?

**Comment by CendioOssman** [comment]
I'd say getting TLS up and running. That is the standard for Windows servers, so it is what gets tested and maintained best. I'm afraid I'm not familiar with VirtualBox enough to say how to make that easier to configure.

**Comment by 3yan** [comment]
I've checked the issue after a while. Version 1.8.6 is problematic, when I tried the master branch it seems to be fixed.
Client - rdekstop - master branch from github compiled few minutes ago and rdesktop 1.8.6.
Host - Virtualbox 6.0.12-2 - windows 7 and windows 10

Issue was present in both virtual machines when rdesktop version 1.8.6 (current version on archlinux) was used and absent when using rdekstop master branch was used.
My original issue is documented here: https://github.com/rdesktop/rdesktop/issues/328#issuecomment-503663129

I am not sure if my case is related to this #319 issue or the #320 issue, however - for me, the thing is "solved." I will try to check this thread for next few days, so if you need any more testing/info I will provide it.

**Comment by CendioOssman** [comment]
That's great. Could some more of you guys test master or the 1.9.0 beta and see if it works for you?

**Comment by Harv234** [comment]
Would like to test too, but can't get going. I am on Archlinux and downloaded the rdesktop master zip file. The  ./configure script seems to be missing. So
% ./configure
% make
% make install
does not work for me. @3yan: Can you add some advice how to build this from source on archlinux? Base-devel is installed, just for the record...

**Comment by CendioOssman** [comment]
Please download the beta from the release page. It will contain a configure script.

**Comment by 3yan** [comment]
@Harv234 - I've took the PKGBUILD from original package and rewrote it in a dirty way. The code below worked for me. If you run into trouble let me know. I've tried it just now with makepkg -f and it worked.

```
# Contributor: Andrea Scarpino <andrea@archlinux.org>
# contributor: dan mcgee <dan@archlinux.org>
# contributor: 3yan <3yanyanyan@gmail.com>

pkgname=rdesktop
pkgver=1.8.6.
pkgrel=666
pkgdesc="An open source client for Windows Remote Desktop Services"
arch=('x86_64')
url="https://www.rdesktop.org/"
license=('GPL3')
depends=('libao' 'libsamplerate' 'xorg-xrandr' 'pcsclite' 'libgssglue')
source=(git+git://github.com/rdesktop/rdesktop.git)
sha512sums=('SKIP')

prepare() {
  cd rdesktop
  ./bootstrap
}

build() {
  cd rdesktop
  ./configure --prefix=/usr \
    --enable-smartcard \
    --with-ipv6
  make
}

package() {
  cd rdesktop
  make DESTDIR="${pkgdir}" install
}

```

**Comment by Harv234** [comment]
Ok, I compiled the 1.9.0 source and my issue is gone - connection to virtualbox rdp is possible again! Good work. 
FWIW - I have this message displayed:
Clipboard(error): xclip_handle_SelectionNotify(), unable to find a textual target to satisfy RDP clipboard text request

**Comment by CendioOssman** [comment]
Glad to hear it. I'll go ahead and close this issue now then. Thanks for testing.

The clipboard error is harmless. It means it failed to find text in the current clipboard, which is perfectly normal if the clipboard contains something else, e.g. an image.
