### ISSUE TITLE
GitHub shows releases based on master branch

### ISSUE THREAD

**Issue by paulmenzel** [rdesktop/rdesktop#324]
Looking at the [releases](https://github.com/rdesktop/rdesktop/releases), GitHub seems to think they are based on the master branch.

For 1.8.3:

> hean01-cendio released this on Aug 17, 2015 · 366 commits to master since this release 

For 1.8.4:

> hean01-cendio released this on Jan 2 · 366 commits to master since this release

Is it possible to tell GitHub, that they are based on the branch 1.8.x?

**Comment by CendioOssman** [comment]
Not as far as I know, no. It will always look for the branch point from master and show you that number. If you want to know the number of commits since 1.8.0 then I'm afraid you'll have to check the difference between the releases.
