### ISSUE TITLE
Rdesktop freezes often

### ISSUE THREAD

**Issue by JordiDai** [rdesktop/rdesktop#329]
Hi all,
I have a set of raspberrys pi 3b connected through rdesktop to a server running  windows 2012. All raspberrys are connected to the same switch. The problem I have is that every two hours or so the program stops and the image freezes. We have done some tests and it seems that the connection is OK. The moment that rdesktops stops is not the same for any raspberry, and some days raspberrys hangs more than other days. I wonder if they know what the problem may be and if there is any solution. 
Thank you

**Comment by CendioOssman** [comment]
Is this a stable release version or `master`? We had something similar reported before and a fix is in the development version.

**Comment by JordiDai** [comment]
I use the version that raspberry installs by default. Version 1.8.3. I don't know if that will give you enough information to solve the problem.
Thanks

**Comment by JordiDai** [comment]
How can I do that?

**Comment by CendioOssman** [comment]
Download and unpack https://github.com/rdesktop/rdesktop/archive/master.zip. Then see the chapters "Note for users building from source" and "Installation" in README.md.

**Comment by CendioOssman** [comment]
No response.
