### ISSUE TITLE
Failed to open display.

### ISSUE THREAD

**Issue by rocky595** [rdesktop/rdesktop#33]
I'm in the process of trying to pipe the results from RDP connections to a file. I tried PowerShell but could not get RDP to pipe terminal services to a file or string for interrogation. I just need to know if a good connection took place, I have dozens of servers to rotate thru.

So, I found rdesktop and I'm more of a LINUX guy, but a little stale. 
When I issue: rdesktop <IP Address> I get:
Failed to open display - 10.999.101.101. 
I set a DISPLAY env variable to my LINUX servers name, but didn't help. I think this is a active X thing. I plan to set the term variable to the LINUX server ip, for some reason that comes to mind.

My goal is to pound dozens of servers using and Expect type of script to see if they are functional. I do this for SSH and using Expect. Works great. RDP is a different beast or I'm missing something.

**Comment by rocky595** [comment]
I have terminal services turned on for the target ip. We RDP to these same servers using MS RDP. 
rdesktop <target ip>
Researching now if terminal services is turned on for my own LINUX VM.

**Comment by hean01-cendio** [comment]
The issue with rdesktop not starting is that it fails to connect to X Display. For the rest, if i understand you correct, you cant use rdesktop in that way.

**Comment by CptJason** [comment]
Hello,

How to fix this ERROR.

   ```
 rdesktop -u xxxxxxxxxxxxx -p -  46.93.139.222
   Password:
   ERROR: Failed to open display:
```

**Comment by mauroacs** [comment]
Developers,
The rdesktop package in its recent version is broken. Targeting failed. Here to work around the problem I came back to version 1.7.1
