### ISSUE TITLE
v1.8.6 doesn't build on Scientifici Linux 6

### ISSUE THREAD

**Issue by andrew-aitchison** [rdesktop/rdesktop#331]
On Scientifici Linux 6 (and presumablly RHEL6 and CentOS 6) configure fails:
configure: WARNING: pkg-config not available, cannot check for libgssglue

Version 1.8.4 build fine; I don't know what has changed in the build environment for the new tarball, but this patch causes configure to be rebuilt on the build machine, and the binaries them build correctly.
 
[rdesktop-1.8.6-bootstrap.patch.txt](https://github.com/rdesktop/rdesktop/files/3219178/rdesktop-1.8.6-bootstrap.patch.txt)

This niggle is a pity since in previous version it was possible to build the binary package from the tarball with the single command
  rpmbuild -ta rdesktop-1.8.4.tar.gz

**Comment by CendioOssman** [comment]
Odd. The new release is generated with a more modern autoconf, but it should be backwards compatible. What does config.log say with regards to looking for pkg-config?

**Comment by andrew-aitchison** [comment]
configure: checking for OpenSSL directory
configure: result: /usr

Around line 280 config.log has
    
    configure:4689: checking for pkg-config
    configure:4707: found /usr/bin/pkg-config
    configure:4719: result: /usr/bin/pkg-config
    
then around line 601 config.log has 
    
    configure: checking for OpenSSL directory
    configure: result: /usr
    configure:5013: checking for OpenSSL directory
    configure:5046: result: /usr
    configure:5153: WARNING: pkg-config not available, cannot check for libgssglue
    
    ## ---------------- ##
    ## Cache variables. ##
    ## ---------------- ##

More interesting (I think) is what is missing in the 1.8.6 log compared to the 1.8.4 log.
Most significantly the 1.8.4 config.log has these lines, but there are no equivant lines in the 1.86 file:

    ac_cv_env_PKG_CONFIG_LIBDIR_set=
    ac_cv_env_PKG_CONFIG_LIBDIR_value=
    ac_cv_env_PKG_CONFIG_PATH_set=set
    ac_cv_env_PKG_CONFIG_PATH_value=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
    ac_cv_env_PKG_CONFIG_set=
    ac_cv_env_PKG_CONFIG_value=

The 1.84 anfd 1.86 config.log files are attached:
[rdesktop.1.8.4.config.log](https://github.com/rdesktop/rdesktop/files/3254340/rdesktop.1.8.4.config.log)
[rdesktop.1.8.6.config.log](https://github.com/rdesktop/rdesktop/files/3254341/rdesktop.1.8.6.config.log)

**Comment by CendioOssman** [comment]
Hmm... I'm not sure what went wrong, but the shipped configure doesn't look quite right. I regenerated the file and the new version looks much better.

I've uploaded a new tar ball for the release. Hopefully it will resolve the issue for you as well.
