### ISSUE TITLE
v1.8.6 and master getting overrun assert failure connecting to xrdp

### ISSUE THREAD

**Issue by amworsley** [rdesktop/rdesktop#333]
Trying to connect to the Debian server running xrdp 0.9.9-1 (Buster) with versions newer than 1.8.4 get an unexpected stream overrun failure.

My debugging shows the older 1.8.4 code had many 00 padded fields and the newer one shows the packet has no-zero's and the length is way too big. 

See below for details

Compiling the 1.8.6 package with Debian and running with debug I get:
<pre>
RDESKTOP_DEBUG=All ./rdesktop    azza
Connection established using plain RDP.
ERROR: rdp.c:128: rdp_recv(), unexpected stream overrun0000 03 00 01 b5 02 f0 80 68 00 01 03 eb 70 81 a6 08 .......h....p...
0010 00 00 00 16 cf 1f 5e f8 58 db c7 8c cb 40 34 5b ......^.X....@4[
0020 08 b2 3b a8 79 da dd b3 1c 50 d5 aa b0 3e a4 01 ..;.y....P...>..
0030 fd 2e d8 e5 06 05 63 92 ca fe 87 db 41 09 7b be ......c.....A.{.
0040 3c f5 4f d8 d6 de bb b1 81 fe c0 2a d3 e5 53 08 <.O........*..S.
0050 16 ee f0 74 b1 01 a8 be 6f 9d 8d b2 96 73 7f b2 ...t....o....s..
0060 32 f5 7b 0d 78 30 f3 24 49 91 52 79 30 e2 a3 06 2.{.x0.$I.Ry0...
0070 ef a8 96 46 ae 54 dc ae 21 ce 7b a0 32 9f 2a 29 ...F.T..!.{.2.*)
0080 d9 4c fc b1 da 37 19 46 b8 3b c1 c7 5a 2b f3 ba .L...7.F.;..Z+..
0090 96 fb d6 2e 44 62 73 b1 2e d4 7e a1 77 ac 91 2e ....Dbs...~.w...
00a0 cd 22 a0 33 fb 8e 26 d1 0e b6 d7 2c 40 7f e0 d2 .".3..&....,@...
00b0 ba 10 ce d1 a0 cf 9a c4 7f 09 95 28 6d 73 a3 fd ...........(ms..
00c0 00 28 e8 9e bc cb a1 d2 5b 98 2a bd d5 b0 78 00 .(......[.*...x.
00d0 31 70 a1 ca 4d b5 41 54 9f e5 83 35 ad c8 60 80 1p..M.AT...5..`.
00e0 fb a3 d9 ad 96 ae 1b d8 22 77 a4 8e e8 12 89 d1 ........"w......
00f0 99 49 6a fa 82 d1 2c 47 32 66 c4 2e 0f 0b 5c 97 .Ij...,G2f....\.
0100 6e b8 dd 23 e3 70 43 12 8b 5d 9c da f7 84 01 d2 n..#.pC..]......
0110 91 a4 7a cd b5 63 45 70 48 5b 8d 81 8f 81 7a 4b ..z..cEpH[....zK
0120 8d 5a b9 93 4f 21 63 26 c2 05 ae c5 0b d2 b2 0a .Z..O!c&........
0130 d5 8d 9f 3b 00 13 d4 fb 32 77 cd 20 a7 61 f1 18 ...;....2w. .a..
0140 fa 6c 1b 51 97 77 96 f1 8a 68 65 28 d7 c7 73 a8 .l.Q.w...he(..s.
0150 15 af c4 1f 1e f9 7f 2f 1f 77 a1 bc 9d a5 f8 74 ......./.w.....t
0160 81 ab 98 5e 28 92 84 f5 e9 29 f7 75 5d 2d 44 97 ...^(....).u]-D.
0170 1b ec 7b de b6 b7 08 c2 31 67 1f ef 54 5c cf 0a ..{.....1g..T\..
0180 db 6d 76 ae bd 02 03 39 43 4a 3f 99 83 cc eb a7 .mv....9CJ?.....
0190 ce 7e 52 d8 16 de b1 c1 f3 5e 56 a8 28 14 48 41 .~R......^V.(.HA
01a0 81 91 66 4d e6 28 ef 12 0d 8d c1 48 f0 64 f5 a4 ..fM.(.....H.d..
01b0 95 b3 5f 9f 15                                  .._..
</pre>

  * I then tried the master branch from github:
commit 231502e (HEAD -> b1.8.x, origin/1.8.x)
Author: Markus Beth <markus.beth@web.de>
Date:   Wed May 22 19:51:40 2019 +0200

    fixed version number and typo
 I tried to trace the failure by building with debug:
<pre>
 diff --git a/rdp.c b/rdp.c
index e7a849b..9be6d46 100644
--- a/rdp.c
+++ b/rdp.c
@@ -129,6 +129,8 @@ rdp_recv(uint8 * type)
        }
 
        in_uint16_le(rdp_s, length);
+        printf("%s: length=%u rdp_s->end - rdp_s->p = %tu\n",
+           __func__, length, rdp_s->end - rdp_s->p);
        /* 32k packets are really 8, keepalive fix */
        if (length == 0x8000)
        {
@@ -136,11 +138,16 @@ rdp_recv(uint8 * type)
                *type = 0;
                return rdp_s;
        }
+       if (length > (rdp_s->end - rdp_s->p)) {
+           printf("%s: invalid length=%u truncating to %td\n",
+               __func__, length, rdp_s->end - rdp_s->p + 2);
+           length = rdp_s->p - rdp_s->data + 2;
+       }
        in_uint16_le(rdp_s, pdu_type);
        in_uint8s(rdp_s, 2);    /* userid */
        *type = pdu_type & 0xf;
 
-#if WITH_DEBUG
+#if 1
        DEBUG(("RDP packet #%d, (type %x)\n", ++g_packetno, *type));
        hexdump(rdp_s->data + g_next_packet, length);
 #endif /*  */
</pre>

  * This yields:
<pre>
RDESKTOP_DEBUG=All ./rdesktop  azza
RDP depth: 24, display depth: 24, display bpp: 32, X server BE: 0, host BE: 0
server bpp 24 client bpp 32 depth 24
Connection established using plain RDP.
g_num_channels is 4
Requesting channel cliprdr
Requesting channel rdpsnd
Requesting channel snddbg
Requesting channel rdpdr
Server RDP version is 4
We're going for the RDP4-style encryption
Got Public key, RDP4-style
Generating client random
rc_4_key_size == 2, 128-bit encryption enabled
Sending CJRQ for channel #1002
Sending CJRQ for channel #1003
Sending CJRQ for channel #1004
Sending CJRQ for channel #1005
Sending CJRQ for channel #1006
Sending CJRQ for channel #1007
Sending RDP5-style Logon packet
Called sec_init with packetlen 330
Sending encrypted packet:
0000 00 00 00 00 33 01 00 00 00 00 06 00 00 00 00 00 ....3...........
0010 00 00 00 00 61 00 6d 00 77 00 00 00 00 00 00 00 ....a.m.w.......
0020 00 00 02 00 14 00 31 00 30 00 2e 00 38 00 2e 00 ......1.0...8...
0030 31 00 2e 00 39 00 37 00 00 00 3c 00 43 00 3a 00 1...9.7...<.C.:.
0040 5c 00 57 00 49 00 4e 00 4e 00 54 00 5c 00 53 00 \.W.I.N.N.T.\.S.
0050 79 00 73 00 74 00 65 00 6d 00 33 00 32 00 5c 00 y.s.t.e.m.3.2.\.
0060 6d 00 73 00 74 00 73 00 63 00 61 00 78 00 2e 00 m.s.t.s.c.a.x...
0070 64 00 6c 00 6c 00 00 00 a8 fd ff ff 47 00 54 00 d.l.l.......G.T.
0080 42 00 2c 00 20 00 6e 00 6f 00 72 00 6d 00 61 00 B.,. .n.o.r.m.a.
0090 6c 00 74 00 69 00 64 00 00 00 00 00 00 00 00 00 l.t.i.d.........
00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0a 00 ................
00c0 00 00 05 00 03 00 00 00 00 00 00 00 00 00 00 00 ................
00d0 47 00 54 00 42 00 2c 00 20 00 73 00 6f 00 6d 00 G.T.B.,. .s.o.m.
00e0 6d 00 61 00 72 00 74 00 69 00 64 00 00 00 00 00 m.a.r.t.i.d.....
00f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0110 00 00 03 00 00 00 05 00 02 00 00 00 00 00 00 00 ................
0120 c4 ff ff ff 00 00 00 00 27 00 00 00 00 00       ........'.....
Received licensing PDU (message type 0x01)
Sending licensing PDU (message type 0x13)
Received licensing PDU (message type 0xff)
rdp_recv: length=48943 rdp_s->end - rdp_s->p = 408
rdp_recv: invalid length=48943 truncating to 410
RDP packet #1, (type e)
0000 2f bf 2e 24 c3 84 d6 ac 73 2c f4 ad 59 63 98 d1 /..$....s,..Yc..
0010 43 f9 28 bc fa 38 7c fb ac 8e b7 f6 20 ed 6c    C.(..8|..... .l
NOT IMPLEMENTED: PDU 14
rdp_recv: length=3268 rdp_s->end - rdp_s->p = 377
rdp_recv: invalid length=3268 truncating to 379
RDP packet #2, (type 1)
0000 c4 0c e1 22 c0 1e 66 86 18 b8 c7 dc fb fb a9 8c ..."..f.........
0010 66 2f c7 bf 84 c9 4a 91 6a f8 36 fb a3 30 6c b5 f/....J.j.6..0l.
0020 e5 35 d8 29 79 0a c3 2b 4e 63 e2 05 a1 d0 aa ad .5.)y..+Nc......
0030 38 83 b2 70 e4 14 8d b9 cd 95 ae 71 ad cd       8..p.......q..
ERROR: rdp.c:1130: process_demand_active(), consume of source descriptor from stream would overrun0000 03 00 01 b5 02 f0 80 68 00 01 03 eb 70 81 a6 08 .......h....p...
0010 00 00 00 0a f4 70 a9 41 1d 0a 9c 2f bf 2e 24 c3 .....p.A.../..$.
0020 84 d6 ac 73 2c f4 ad 59 63 98 d1 43 f9 28 bc fa ...s,..Yc..C.(..
0030 38 7c fb ac 8e b7 f6 20 ed 6c c4 0c e1 22 c0 1e 8|..... .l..."..
0040 66 86 18 b8 c7 dc fb fb a9 8c 66 2f c7 bf 84 c9 f.........f/....
0050 4a 91 6a f8 36 fb a3 30 6c b5 e5 35 d8 29 79 0a J.j.6..0l..5.)y.
0060 c3 2b 4e 63 e2 05 a1 d0 aa ad 38 83 b2 70 e4 14 .+Nc......8..p..
0070 8d b9 cd 95 ae 71 ad cd 0b b4 a5 08 44 80 1e 96 .....q......D...
0080 25 17 4f 11 ba cf ec bd e3 2b 8a c0 e3 c8 e6 88 %.O......+......
0090 89 cc e9 8d f6 e1 51 57 0b 9d 22 fb f4 d4 96 61 ......QW.."....a
00a0 db 5a cd bb 34 8a e4 c4 5b bb 96 da a9 49 34 70 .Z..4...[....I4p
00b0 65 f7 6d 4b 72 8a 0a 52 1f 03 d6 c2 41 7f d7 b7 e.mKr..R....A...
00c0 48 61 f9 ac b6 35 3b 0b f4 a1 30 27 dd e1 fe 43 Ha...5;...0'...C
00d0 40 83 68 d2 b3 1c 07 da e1 f9 dd f8 21 79 d9 8e @.h.........!y..
00e0 6f 11 3f 9f 64 26 5a 55 54 34 11 c8 90 0d 7c 79 o.?.d&ZUT4....|y
00f0 be c7 8d 45 5f c2 42 7b 9d 70 e4 9c e8 07 b3 67 ...E_.B{.p.....g
0100 5a 09 a3 78 20 7b fc 2c c2 54 f7 04 8e c1 a0 c5 Z..x {.,.T......
0110 56 40 8d cd b1 c9 da 67 ce 96 a6 ab 53 ca 60 10 V@.....g....S.`.
0120 18 a0 58 03 7b 42 26 d8 52 7b c6 04 13 5d b4 91 ..X.{B&.R{...]..
0130 5f 2d ee 81 f9 2a 45 5d cc d5 92 be c5 d1 6c 39 _-...*E]......l9
0140 c9 7c 16 8e d4 93 f2 ce 3e 38 f6 85 d8 34 45 32 .|......>8...4E2
0150 3f 8d 05 2a d4 24 7e 17 da ea b4 3a ac 2f 36 a1 ?..*.$~....:./6.
0160 ff 6b 55 91 9c 88 fe a3 ff 5e 0a 33 aa a5 d2 ef .kU......^.3....
0170 c1 42 86 08 31 0c 41 6b 82 cd c7 ca ea 5f 97 74 .B..1.Ak....._.t
0180 9a 10 f9 6d d7 a7 e9 ca 37 36 82 ba 96 22 96 fa ...m....76..."..
0190 42 3a 25 5f 8a 12 32 0a 45 9e 26 58 00 f1 8c 40 B:%_..2.E.&X...@
01a0 5a 39 55 89 93 1e 0a 71 c8 fb c7 e9 ab 50 a7 7d Z9U....q.....P.}
01b0 c8 fe 09 dd 13                                  .....
</pre>
  * Please compare this with the similarly patched 1.8.4 code which works (connects and doesn't crash):
<pre>
RDESKTOP_DEBUG=All ./rdesktop  azza
Connection established using plain RDP.
rdp_recv: length=410 rdp_s->end - rdp_s->p = 408
0000 9a 01 11 00 ea 03 ea 03 01 00 04 00 84 01 52 44 ..............RD
0010 50 00 0d 00 00 00 09 00 08 00 ea 03 b5 e2 01 00 P...............
0020 18 00 01 00 03 00 00 02 00 00 00 00 01 04 00 00 ................
0030 00 00 00 00 00 00 02 00 1c 00 18 00 01 00 01 00 ................
0040 01 00 20 03 58 02 00 00 01 00 01 00 00 00 00 00 .. .X...........
0050 00 00 0e 00 04 00 03 00 58 00 00 00 00 00 00 00 ........X.......
0060 00 00 00 00 00 00 00 00 00 00 40 42 0f 00 01 00 ..........@B....
0070 14 00 00 00 01 00 2f 00 22 00 01 01 01 01 00 00 ....../.".......
0080 00 00 01 00 01 00 00 00 00 00 00 00 01 00 00 00 ................
0090 00 00 00 00 00 01 00 00 00 00 a1 06 02 00 40 42 ..............@B
00a0 0f 00 40 42 0f 00 01 00 00 00 00 00 00 00 1d 00 ..@B............
00b0 5d 00 04 b9 1b 8d ca 0f 00 4f 15 58 9f ae 2d 1a ]........O.X..-.
00c0 87 e2 d6 01 03 00 01 01 03 12 2f 77 76 72 bd 63 ........../wvr.c
00d0 44 af b3 b7 3c 9c 6f 78 86 00 04 00 00 00 00 00 D...<.ox........
00e0 d4 cc 44 27 8a 9d 74 4e 80 3c 0e cb ee a1 9c 54 ..D'..tN.<.....T
00f0 00 04 00 00 00 00 00 e6 4c af 1b ed 9e 0c 43 86 ........L.....C.
0100 9a cb 8b 37 b6 62 37 00 01 00 4b 0a 00 08 00 06 ...7.b7...K.....
0110 00 00 00 08 00 0a 00 01 00 19 00 19 00 0d 00 58 ...............X
0120 00 3d 01 00 00 00 00 00 00 00 00 00 00 00 00 00 .=..............
0130 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0140 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0150 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0160 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0170 00 00 00 00 00 06 00 05 00 00 1a 00 08 00 00 00 ................
0180 30 00 1e 00 08 00 02 00 00 00 1c 00 0c 00 52 00 0.............R.
0190 00 00 00 00 00 00 00 00 00 00                   ..........
rdp_recv: length=22 rdp_s->end - rdp_s->p = 20
0000 16 00 17 00 ea 03 ea 03 01 00 00 01 16 00 1f 00 ................
0010 16 00 01 00 ea 03                               ......
rdp_recv: length=26 rdp_s->end - rdp_s->p = 24
0000 1a 00 17 00 ea 03 ea 03 01 00 00 01 1a 00 14 00 ................
0010 1a 00 04 00 00 00 ea 03 00 00                   ..........
rdp_recv: length=26 rdp_s->end - rdp_s->p = 24
0000 1a 00 17 00 ea 03 ea 03 01 00 00 01 1a 00 14 00 ................
0010 1a 00 02 00 00 00 ea 03 00 00                   ..........
rdp_recv: length=26 rdp_s->end - rdp_s->p = 24
0000 1a 00 17 00 ea 03 ea 03 01 00 00 01 1a 00 28 00 ..............(.
0010 1a 00 00 00 00 00 03 00 04 00                   ..........
</pre>

For what it is worth playing with -e / -E (encryption) doesn't help much.
 With -E - still crashes similarly but with -e it endlessly seems to be looping processing type 0 packets. 
Note: Even version 1.8.4 doesn't work with -e either though.

**Comment by maoxuner** [comment]
I have the save issue when connecting to virtualbox(6.0.2-128162~Debian~stretch) with rdesktop newer than 1.8.4.

**Comment by CendioOssman** [comment]
Could you check if `master` or the current `1.8.x` branch works better? A fix was just applied.

**Comment by maoxuner** [comment]
@CendioOssman Current `1.8.x` branch works well on my laptop.

However, it requires me a password when it is `master` branch. Actually, there is no password.
```
./rdesktop 192.168.0.111:3389
Autoselecting keyboard map 'en-us' from locale
Password:
```

**Comment by amworsley** [comment]
I replied by email - but the same as above.

The latest rev 7841030 is working for me - so please release that

The master gives the "Password:" prompt and no matter what I type (even just enter) it prints:
<pre>Connection established using plain RDP.</pre>
 immeadiately exits with exit status 76 - which is EX_PROTOCOL as defined in rdesktop.h

**Comment by CendioOssman** [comment]
> @CendioOssman Current `1.8.x` branch works well on my laptop.
> 

Great.

> However, it requires me a password when it is `master` branch. Actually, there is no password.

That is per design. We're trying to mimic how Microsoft's own client behaves as it is very difficult for us to handle clusters and redirections otherwise. There should be existing issues about this.

**Comment by CendioOssman** [comment]
> immeadiately exits with exit status 76 - which is EX_PROTOCOL as defined in rdesktop.h

This should be some other bug. Please open a separate issue.
