### ISSUE TITLE
sound support

### ISSUE THREAD

**Issue by alegrej** [rdesktop/rdesktop#335]
i'm doing the sound redirection from my remote desktop, the sounds from windows/youtube works fine, but other apps like skype for business didn't work, the app don't recognize a headset.
the other thing i'm trying to do is the microphone redirection, it's possible?
i'm using the version 1.8.4 of the rdesktop on a raspberry pi 3 with raspbian

**Comment by CendioOssman** [comment]
No, a microphone is currently not supported. Please see #323.
