### ISSUE TITLE
master version fails connecting to xrdp program - exits with EX_PROTOCOL

### ISSUE THREAD

**Issue by amworsley** [rdesktop/rdesktop#336]
Fails connecting to xrdp program whilst the 1.8.4. version is fine (and the stable branch rev 7841030 is ok too)
----
Latest master is rev 1475092  :
<pre>
commit 1475092 (HEAD -> master, origin/master, origin/HEAD)
Author: Pierre Ossman <ossman@cendio.se>
Date:   Thu Jun 13 14:23:02 2019 +0200

    Avoid nesting stream macros
    
    It only works by luck here, so avoid this style as bugs easily happen.

M       channels.c
</pre>
====
This builds fails trying to connect to xrdp package whilst the stable branch is ok - truncated output is:
<pre>
RDESKTOP_DEBUG=All ./rdesktop  localhost  macbook: 4:25PM
Password: 
UI(debug): RDP depth: 24, display depth: 24, display bpp: 32, X server BE: 0, host BE: 0

Keyboard(debug): add_to_keymap(), adding translation, keysym=0xffe2, scancode=0x36, modifiers=0x0
Keyboard(debug): add_to_keymap(), adding translation, keysym=0xffe1, scancode=0x2a, modifiers=0x0
...
Keyboard(debug): add_to_keymap(), adding translation, keysym=0x3f, scancode=0x35, modifiers=0x2
is_wm_active(): WM name: Flux
Core(debug): dvc_channels_add(), Added hash=67f73722, channel_id=-1, name=Microsoft::Windows::RDS::DisplayControl, handler=0x55fc15a6f960
Protocol(debug): rdp_reset_state()
Protocol(debug): mcs_connect_start()
Connecting to server using NLA...
Core(debug): tcp_connect(), trying localhost (127.0.0.1)
Connection established using plain RDP.
Protocol(debug): sec_out_mcs_connect_initial_pdu()
Protocol(debug): sec_out_mcs_data(), g_num_channels is 5
Protocol(debug): sec_out_mcs_data(), requesting channel cliprdr
Protocol(debug): sec_out_mcs_data(), requesting channel rdpsnd
Protocol(debug): sec_out_mcs_data(), requesting channel snddbg
Protocol(debug): sec_out_mcs_data(), requesting channel rdpdr
Protocol(debug): sec_out_mcs_data(), requesting channel drdynvc
Protocol(debug): mcs_connect_finalize()
Protocol(debug): mcs_send_connect_initial()
Protocol(debug): mcs_recv_connect_response()
Protocol(debug): sec_process_mcs_data()
Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_INFO
Protocol(debug): sec_process_srv_info(), server RDP version is 4
Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_CHANNELS
Protocol(debug): sec_process_mcs_data(), SEC_TAG_SRV_CRYPT
Protocol(debug): sec_process_crypt_info()
Protocol(debug): sec_parse_crypt_info()
Protocol(debug): sec_parse_crypt_info(), We're going for the RDP4-style encryption
Protocol(debug): sec_parse_crypt_info(), got public key
Protocol(debug): sec_parse_crypt_info(), generating client random
Protocol(debug): sec_generate_key(), rc_4_key_size == 2, 128-bit encryption enabled
Protocol(debug): mcs_send_edrq()
Protocol(debug): mcs_send_aurq()
Protocol(debug): mcs_recv_aucf()
Protocol(debug): mcs_send_cjrq(), chanid=1002
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1003
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1004
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1005
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1006
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1007
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): mcs_send_cjrq(), chanid=1008
Protocol(debug): mcs_recv_cjcf()
Protocol(debug): rdp_send_logon_info(), sending RDP5-style Logon packet
Protocol(debug): rdp_send_logon_info(), called sec_init with packetlen 330
</pre>
   - Exits at this point with status 76 - presumably EX_PROTOCOL

**Comment by CendioOssman** [comment]
So it seems the server is dropping us rather than we getting upset about something the server sent.

Have you checked if there are is anything in the server log?

Do you think you could do a `git bisect` to see where things started breaking?

**Comment by CendioOssman** [comment]
This might have some overlap with #319. The output looks very similar, but that issue states it was broken in 1.8.4 as well.

**Comment by CendioOssman** [comment]
No response.
