### ISSUE TITLE
failed to negotiate protocol

### ISSUE THREAD

**Issue by razaqq** [rdesktop/rdesktop#339]
Trying to connect, but ending up with the following errors. depending on the flags i use.

```
$ rdesktop -g 100% -P -z -x l -r sound:off -u User ip:port
Autoselected keyboard map en-us
Failed to negotiate protocol, retrying with plain RDP.
NOT IMPLEMENTED: PDU 13
ERROR: rdp.c:128: rdp_recv(), unexpected stream overrun
```
followed by a bunch of hex codes.  

without compression:
```
$ rdesktop -g 100% -P -x l -r sound:off -u User ip:port
Autoselected keyboard map en-us
Failed to negotiate protocol, retrying with plain RDP.
ERROR: xmalloc -583575531
```

without compression and lan mode:
```
$ rdesktop -g 100% -P -u User ip:port              
Autoselected keyboard map en-us
Failed to negotiate protocol, retrying with plain RDP.
ERROR: Protocol error in server redirection, unexpected data.ERROR: rdp.c:284: rdp_in_unistr(), consume of unicode data from stream would overrun
```
followed again by hex codes

and finally without bitmap caching:
```
rdesktop -g 100% -u User ip:port
Autoselected keyboard map en-us
Failed to negotiate protocol, retrying with plain RDP.
ERROR: rdp.c:1123: process_demand_active(), consume of source descriptor from stream would overrun
```

Target OS: Windows 10 x86_64
Client OS: Arch Linux with kernel 4.19.53-1-lts x86_64
Client version: 1.8.6

If you need any more information I forgot to add, just lmk

**Comment by CendioOssman** [comment]
Could you test with the current 1.8.x branch? Or with master? There has been another fix since 1.8.6.

**Comment by razaqq** [comment]
okay so i compiled master branch from source and its got giving me the same error anymore.
Im actually getting to the password prompt but am greeted afterwards by this error:
```
Autoselecting keyboard map 'en-us' from locale
Password: 
Protocol(warning): Protocol negotiation failed with reason: SSL not allowed by server
Retrying with plain RDP.
Protocol(error): rdp.c:184: rdp_recv(), not enough data for PDU
```

I tried disabling encryption with first `-e`, then `-E` and then both. However got this error then:
```Autoselecting keyboard map 'en-us' from locale
Password: 
Protocol(warning): Protocol negotiation failed with reason: SSL not allowed by server
Retrying with plain RDP.
Core(error): tcp_recv(), recv() failed: Connection reset by peer
```

**Comment by tropikhajma** [comment]
I'm observing the same thing trying to connect to a VirtualBox VM.
I'm on Mageia Linux 7, rdesktop 1.8.5

**Comment by CendioOssman** [comment]
VirtualBox is handled on #319, and let's merge all the plain RDP problems on #320.
