### ISSUE TITLE
rdesktop 1.8.5 and 1.8.6 do not connect to Virtualbox rdp server while 1.8.4 does

### ISSUE THREAD

**Issue by Harv234** [rdesktop/rdesktop#340]
when connecting to an Virtualbox rdp Server, 1.8.6 bails out with:
failed to negotiate protocol, retrying with plain RDP.
NOT IMPLEMENTED: PDU 14
ERROR: rdp.c:128: rdp_recv(), unexpected stream overrun0000 03 00 01 41 02 f0 80 68 00 01 03 eb 70 81 32 08 ...A...h....p.2.
0010 00 00 00 5f a5 83 bc 63 12 b6 7e b5 c3 fe ed a4 ..._...c..~.....
0020 15 1f 5c 81 42 db 0a 3c f8 01 a1 92 09 ec 88 93 ..\.B..<........
0030 0e 00 3d 89 3f 5d d7 15 32 f9 9f db 40 c4 a2 37 ..=.?]..2...@..7
0040 33 91 a2 37 c6 ee dd f9 92 c6 ca 06 87 19 58 90 3..7..........X.
0050 12 a0 4e cf 11 ef 51 7e 88 02 3a 6d 90 7d e9 0b ..N...Q~..:m.}..
0060 a8 89 ed 2a f8 5c 30 0b 41 c1 42 18 23 6d 6d 75 ...*.\0.A.B.#mmu
0070 61 1b ea 15 10 b4 4d cd fd 79 67 6c 97 1a a4 e7 a.....M..ygl....
0080 69 8a 4d bc 46 d7 15 4f e8 75 cc 59 8c 1d ed cd i.M.F..O.u.Y....
0090 14 51 d7 81 4c 3e 9b c0 83 f6 5f 3d e1 93 83 9d .Q..L>...._=....
00a0 da 2f 0a 5b 6b cb 34 4b 75 1c cd 70 c7 b5 e4 7d ./.[k.4Ku..p...}
00b0 b0 3a 70 aa 8b 3c 51 89 28 ba 5d 2a a5 f4 2c ab .:p..<Q.(.]*..,.
00c0 0f 68 df 80 92 37 fd 1c a6 a7 ad 2a 4f d5 7a f9 .h...7.....*O.z.
00d0 0e 8c 42 60 f2 f3 4e b7 65 32 b9 17 4a 64 1d 67 ..B`..N.e2..Jd.g
00e0 03 86 98 c6 d0 ea 08 0a dd 6f eb 49 0e 87 59 8c .........o.I..Y.
00f0 90 d7 40 e7 88 a8 e2 36 37 87 5f 86 25 c6 5b 54 ..@....67._.%.[T
0100 df 90 4d fa 13 13 d4 ca aa 01 78 aa 9b 06 18 7a ..M.......x....z
0110 80 a9 b4 30 4a a2 68 88 08 1d 7a d9 ae ea 1c 58 ...0J.h...z....X
0120 52 93 36 31 e1 ef 4b f4 e8 93 cd 71 ee 97 79 a6 R.61..K....q..y.
0130 41 b6 7e 81 8f 3d d5 48 29 27 7a c9 52 79 e2 5b A.~..=.H)'z.Ry.[
0140 61                                              a

rdesktop 1.8.4 does connect to the same server:
Failed to negotiate protocol, retrying with plain RDP.
WARNING: Remote desktop changed from 2560x1440 to 1920x1080.
ERROR: RDPSND: Extra RDPSND_NEGOTIATE in the middle of a session

**Comment by Harv234** [comment]
Forgot to mention: I am on archlinux, latest kernel 5.1.16

**Comment by tropikhajma** [comment]
I've bisected the sources.
The last commit that worked for me was
commit 166d1bc14d34c20dd0c640571a749a6599180367
Author: Alexander Zakharov <uglym8@gmail.com>
Date:   Thu Aug 31 23:08:09 2017 +0300

    Replace OpenSSL with GnuTLS for all network communications

The next one broke it:
commit 90fd660803282713c3e2d29207dc26255f2e3899
Author: Alexander Zakharov <uglym8@gmail.com>
Date:   Thu Aug 31 23:17:30 2017 +0300

    Parse X.509 certificate, get RSA public key, RSA encrypt
    
    Also add support older (< 3.5.0) GnuTLS versions

**Comment by CendioOssman** [comment]
Please see #319 and #320. There seems to be multiple issues connecting to VirtualBox.
