### ISSUE TITLE
rdesktop 1.8.6 fails to connect to Windows SBS 2003 (1.8.4 works)

### ISSUE THREAD

**Issue by l3u** [rdesktop/rdesktop#341]
Hi :-)

I have a Windows SBS 2003 installation inside a qemu virtual machine I connect to from a Gentoo machine. Until now, everything worked without a problem. I just updated to version 1.8.6, and I can't connect anymore, using the same call:

    $ rdesktop -x l 192.168.x.x -u x -p x -g 1200x830
    Autoselected keyboard map de
    Failed to negotiate protocol, retrying with plain RDP.
    ERROR: rdp.c:1123: process_demand_active(), consume of source descriptor from stream would overrun0000 03 00 01 82 02 f0 80 68 00 01 03 eb 70 81 73 08 .......h....p.s.
    0010 00 02 03 4e 14 a2 fe 80 67 f2 c3 6e 19 81 50 85 ...N....g..n..P.
    0020 e5 3c 3a bb e4 81 f7 74 4d c2 35 e8 29 68 e9 15 .<:....tM.5.)h..
    0030 6b a6 1f 9c d8 2d 1c cb af c2 76 cb a0 f3 f7 4e k....-....v....N
    0040 b1 b1 2b 3f 09 1b 7c 47 44 58 94 58 f6 a1 c2 25 ..+?..|GDX.X...%
    0050 7f 20 74 4b bf 3b 22 51 6e e4 a2 44 9b ca 8e b6 . tK.;"Qn..D....
    0060 db 6f 63 6a 80 c3 3e 1c 45 b0 91 b9 d5 e8 ec 50 .ocj..>.E......P
    0070 27 88 f7 5a 64 0f 46 8e 7c c8 7a f2 b4 f0 96 f3 '..Zd.F.|.z.....
    0080 57 0b db c4 fc 67 94 e5 a5 32 31 9d 40 69 53 38 W....g...21.@iS8
    0090 d5 5e 15 63 f8 65 a2 9a 72 eb 88 8f 7d 50 5a 0c .^.c.e..r...}PZ.
    00a0 0a 16 b3 3a 1a d1 a8 36 e7 d7 03 09 41 50 4a 34 ...:...6....APJ4
    00b0 da 6d eb f2 02 39 f9 f3 39 61 44 9d 75 4b dc b3 .m...9..9aD.uK..
    00c0 fd 89 77 6f 70 56 e8 8e 7a 94 34 05 49 78 84 a3 ..wopV..z.4.Ix..
    00d0 1b 3c 4e 28 31 25 1c 41 94 de 14 9f 17 05 2a ec .<N(1%.A......*.
    00e0 dc 0b 61 61 be 7d ee 00 53 58 80 c2 9d 2a ba aa ..aa.}..SX...*..
    00f0 0f 1c 89 5f 53 cd ab 18 6c e9 0a 8e cb 30 16 1c ..._S...l....0..
    0100 31 cf 10 43 40 91 7f 30 ab 93 45 ef d3 61 45 01 1..C@..0..E..aE.
    0110 cc 02 2d 72 8b 80 82 2f 44 95 84 54 70 aa 5e 9e ..-r.../D..Tp.^.
    0120 84 57 0a 16 3b 97 c8 f4 b5 23 4c 6a 3e be d4 1e .W..;....#Lj>...
    0130 de 4b b6 c2 be f4 e7 b6 d2 00 40 16 a2 0d 8e f2 .K........@.....
    0140 31 d5 eb d2 7f d7 86 75 99 4a c7 59 1d f4 85 e1 1......u.J.Y....
    0150 3e 13 81 2a 0c 8f c1 d7 66 f6 1a 32 c4 57 02 01 >..*....f..2.W..
    0160 8a 8e f4 eb 5a 16 28 0c db 07 5f e8 ae 90 85 ae ....Z.(..._.....
    0170 29 a4 72 3c 65 08 35 7e b0 f0 90 26 cd 8a 86 f1 ).r<e.5~...&....
    0180 60 57

I then downgraded again to version 1.8.4, and it works again without a problem. Please tell me if I can help to track this down!

Cheers, Tobias

**Comment by CendioOssman** [comment]
Please see #320.
