### ISSUE TITLE
Arrow and whole numpad not works connecting to windows 2003 and windows 7

### ISSUE THREAD

**Issue by gzivdo** [rdesktop/rdesktop#343]
rdesktop.git -n abcde -k en-us -L utf-8 -u admin -g 1150x960 -a 16 -r sound:remote <ip>  -r disk:p=/tmp -p ""

Version from ubuntu 18.04 was working fine, but from 19.04 cannot connect to win2003 and I tried version from git, but it have issues with all arrow, keypad, home,end,etc keys.

And with -u and without -p "" it asks password, but should not!

**Comment by CendioOssman** [comment]
What log output are you getting from rdesktop?

**Comment by gzivdo** [comment]
Sorry. Really strange, I recompiled it again and numpad keys starts to work. 

Anyway - p"" should be fixed, it should start without "-p" and send only username without trying to login as it was before.

**Comment by CendioOssman** [comment]
Very odd. I'll go ahead and close this issue then. Thanks for following up.
