### ISSUE TITLE
Regression for TLS version selection argument

### ISSUE THREAD

**Issue by cnotin** [rdesktop/rdesktop#345]
PR #285 added support for TLS 1.1 and 1.2 through the `-V` argument:
https://github.com/rdesktop/rdesktop/blob/a88cd226bb9d5e3c56c0e78b7dd62db86e97e383/rdesktop.c#L190

This is copied in `g_tls_version`:
https://github.com/rdesktop/rdesktop/blob/a88cd226bb9d5e3c56c0e78b7dd62db86e97e383/rdesktop.c#L833-L835

But currently this variable isn't used much... It looks like its usage to specify the TLS version was removed when switching from OpenSSL to GnuTLS (PR #298):
https://github.com/rdesktop/rdesktop/commit/166d1bc14d34c20dd0c640571a749a6599180367#diff-b716ceb55614927ea49ce312f9f86ac5L320-L335

This is confirmed by verifying the TLS version requested in the ClientHello message: always TLS1.2 in my case, even when selection TLS 1.0 or 1.1. Actually any garbage value like "abcd" is also accepted.

Suggestion: re-implement it with GnuTLS

**Comment by CendioOssman** [comment]
Thanks. I'll have a look at getting this supported again.

**Comment by CendioOssman** [comment]
Should be fixed in 256d8e2b3c482616fa3904fdc009cf14ae439046.

**Comment by cnotin** [comment]
Thanks!
