### ISSUE TITLE
New version 1.9.0 GnuTLS required missing

### ISSUE THREAD

**Issue by IanBlakeley** [rdesktop/rdesktop#351]
Configure tells me "rdesktop requires GnuTLS. Please install the dependency" the only one I find is libcurl4-gnutls-dev is this the correct one? If so it wants me to uninstall libcurl4-openssl-dev which is in use for other packages. Is there a way to have both?

Linux MINT 19.1
Linux bilbo2 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by CendioOssman** [comment]
Those packages är för libcurl, so I'm afraid they are not the right ones. I think the package is called `libgnutls28-dev` on Debian derivatives such as Mint.

Hopefully that should get you going. :)

**Comment by IanBlakeley** [comment]
Thanks. That is the correct one, hopefully helps another

**Comment by Cong0ks** [comment]
> Those packages är för libcurl, so I'm afraid they are not the right ones. I think the package is called `libgnutls28-dev` on Debian derivatives such as Mint.
> 
> Hopefully that should get you going. :)

So did I, but my system is Centos6
I tried  gnutls-devel ，but I The attempt failed
