### ISSUE TITLE
./configure doesnt exist

### ISSUE THREAD

**Issue by T0MuX** [rdesktop/rdesktop#353]
Hello, everything is in the title :)

Following the procedure, I did : 
```
git clone https://github.com/rdesktop/rdesktop
cd rdesktop
./configure
```

But the file configure doesnt exist, so it can't be ran.

**Comment by CendioOssman** [comment]
I'm afraid things are only that simple for releases. When working from git you also need to check the chapter "Note for users building from source" which states that `./bootstrap` needs to be run.
