### ISSUE TITLE
first Install rdesktop 19 (centos6, centos7) same Issues , about "libXcursor " problem

### ISSUE THREAD

**Issue by Cong0ks** [rdesktop/rdesktop#359]
Hi, if you free .please help me see it.

My environment:
CentOS release 6.10 (Final)
CentOS Linux release 7.7.1908 (Core)
I used way:
./configure --prefix=/usr/bin/rdesktop19 --disable-credssp --disable-smartcard

`checking build system type... x86_64-redhat-linux-gnu
checking host system type... x86_64-redhat-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... no
checking for pkg-config... /usr/bin/pkg-config
checking for library containing __gmpz_init... no
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/modem.h usability... no
checking sys/modem.h presence... no
checking for sys/modem.h... no
checking sys/filio.h usability... no
checking sys/filio.h presence... no
checking for sys/filio.h... no
checking sys/strtio.h usability... no
checking sys/strtio.h presence... no
checking for sys/strtio.h... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for strip... strip
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XRANDR... no
checking for XCURSOR... no

rdesktop requires libXcursor, install the dependency
`

![c6](https://user-images.githubusercontent.com/14243633/70487422-45b39a80-1b30-11ea-9e11-3b83cb5e6004.jpg)
![c7](https://user-images.githubusercontent.com/14243633/70487430-4e0bd580-1b30-11ea-8b12-3d32c1c4836b.jpg)

Why?   What's the happened?

**Comment by opoplawski** [comment]
You need libXcursor-devel and libXrandr-devel to compile programs that use those libraries.

**Comment by CendioOssman** [comment]
Indeed. When compiling programs the "-devel" packages are needed and the normal ones are not sufficient.
