### ISSUE TITLE
Very... Very slow while X Forward...

### ISSUE THREAD

**Issue by olegon-ru** [rdesktop/rdesktop#360]
I connected by SSH from Fedora Linux to Fedora Linux, run rdesktop on it and forward X. 
When I using 1.8.6 it's no problem, works, as I near server. But after upgrade rdesktop to 1.9.0 it's very sllloooooowwww... 
[Video](https://imgur.com/a/OkIVtzi)
Can you recommend me any command line switch to return previous behaviour?

**Comment by CendioOssman** [comment]
Unfortunately I'm not aware of any switches that will change this. Using X forwarding is not a target use case for rdesktop. The entire point of the project is to provide efficient remote access, something X11 does not provide. Please try to make sure that rdesktop is running directly on your local device, or use something like VNC between the Linux devices if that is not possible.
