### ISSUE TITLE
Core(error): tcp_connect(), unable to connect to xxx

### ISSUE THREAD

**Issue by haoxianhan** [rdesktop/rdesktop#378]
rdesktop -v  -u haoxian 192.168.11.159

it always works but failed as far

Autoselecting keyboard map 'en-us' from locale
is_wm_active(): WM name: i3
Connecting to server using NLA...
Core(error): tcp_connect(), unable to connect to 192.168.11.159

**Comment by antime** [comment]
I meet the same error

**Comment by AnasBawazir** [comment]
same issue here 
any suggestions?

**Comment by surajsahani** [comment]
same here any update^ i am not able to connect

**Comment by yanchingyu** [comment]
Turn off your host firewall

**Comment by FlexESA** [comment]
still no one answer this questions!  i met the same err and searched everywhere to find out the solution but its not there. 
some solutions said access the rdp from a non-root account. i did that but it failed to access it. 

help people!

**Comment by polinazhang** [comment]
Perhaps the IP address you're connecting to has been changed. That's my case.

**Comment by khurshid-tanwir** [comment]
I got solution

**Comment by qiuluo-oss** [comment]
@khurshid-tanwir How did you solve it?
