### ISSUE TITLE
DNSSEC validation failure for homepage (rdesktop.org)

### ISSUE THREAD

**Issue by yurikoles** [rdesktop/rdesktop#382]
From https://dns.google.com/query?name=rdesktop.org:

```
{
  "Status": 2,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "rdesktop.org.",
      "type": 1
    }
  ],
  "Comment": "DNSSEC validation failure. Check http://dnsviz.net/d/rdesktop.org/dnssec/ and http://dnssec-debugger.verisignlabs.com/rdesktop.org for errors"
}
```

**Comment by CendioOssman** [comment]
Not sure what has happened here. @eigenmatt, I think you still control this domain?

**Comment by eigenmatt** [comment]
Hm, I haven't changed anything, it looks like a stuff-up on the part of the DNS hosting provider.  I've temporarily disabled DNSSEC and will re-enable in a few days once they fix it.

**Comment by CendioOssman** [comment]
Seems to be working again. I do notice a bug in the zone though. It has:

```
rdesktop.org.		1800	IN	CNAME	rdesktop.github.io.
```

This is unfortunately not okay and I'm impressed it even works. It's not valid to have `CNAME` on the top level like that as it obscures other crucial records (like `SOA` and `NS`). What you need to do is have `A` entries for github's servers. Compare with TigerVNC:

```
tigervnc.org.		5748	IN	A	185.199.110.153
tigervnc.org.		5748	IN	A	185.199.108.153
tigervnc.org.		5748	IN	A	185.199.109.153
tigervnc.org.		5748	IN	A	185.199.111.153
```

It wouldn't surprise me if this is what screwed up DNSSEC as it might mess up some of those records.

**Comment by eigenmatt** [comment]
Ah, good find.  It's been like that for many years, but you're right that's not a good idea.

I've changed the CNAME to an ALIAS (dynamically flattened to A records at the nameserver) and reenabled DNSSEC.

**Comment by CendioOssman** [comment]
Seems to be working fine now. Thanks for having a look.
