### ISSUE TITLE
SeamlessRDP? How to use? Not working!

### ISSUE THREAD

**Issue by babel68** [rdesktop/rdesktop#39]
This is:
`rdesktop -A -s «c:\seamlessrdp\seamlessrdpshell.exe c:\notepad» 10.7.0.1 -u testadmin -p testadmin`
not working
How right it work?

**Comment by hean01-cendio** [comment]
It depends on version of rdesktop. Check the help page using --help argument. For later version you use it like:
`rdesktop -A "c:\seamlessrdp\seamlessrdpshell.exe` -s "notepad" <server> -u <username> -p <password>
