### ISSUE TITLE
Where is a .configure file?[BUG] 

### ISSUE THREAD

**Issue by Potapov-Ilya** [rdesktop/rdesktop#400]
I have downloaded 1.9.0 version and unpacked it. But cant start compiling because not found .configure file mentioned in READ.me file. Is that a new way to install it? How I can resolve it?

**Comment by oldlavender** [comment]
Hello!

In the `README.md` file there is a section "**Notes for users building from source**" for users obtaining it from git. Before doing the regular steps, if you downloaded it from GIT you must first run the `./bootstrap` script before running `./configure`.

That's a known point of improvement necessary on the `README.md` with ongoing edits. We apologize for the inconvenience!

I'll close this issue, but feel free to open again if you're still not able to build after that. And stay tuned, the `patches` branch has an important recent update and is receiving others soon, and the `next` branch will receive some feature changes soon!
