### ISSUE TITLE
Installation is not working....

### ISSUE THREAD

**Issue by mroricardo** [rdesktop/rdesktop#41]
Hi there!

I have an issue when I try to install rdesktop on Debian 64. I download it correctly, however, when I try to install it using apt-get install, it shows a message saying: "It's not possible to find rdesktop package". I started using Linux not so long and I'm a completely newbie, but on my old Linux distribution (Fedora), it worked fine. What is wrong with it, please?

Thank you very much!

**Comment by hean01-cendio** [comment]
Hi, this is the upstream project of rdesktop and we do not provide any binary packages for any distribution. Only the source are available here. If you can't install rdesktop in debian using apt-get install rdesktop, the distribution does not package rdesktop. Your option is to download and build rdesktop from source.
