### ISSUE TITLE
bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by ashishdoneriya** [rdesktop/rdesktop#47]
When i run ./configure, it says
bash: ./configure: No such file or directory

**Comment by hean01-cendio** [comment]
There are instructions in the README file with the source package, how to build rdesktop from source.

**Comment by ashishdoneriya** [comment]
I followed the instructions in the README file. It says first you have to run the command "./configure". It means it wants us to execute a script named as "configure" which doesn't exists in the entire project.

So either readme is wrong or you have forget to put configure script.

**Comment by hean01-cendio** [comment]
This is found in readme:

> Note for users building from source
> -----------------------------------
> If you have retreived a snapshot of rdesktop source, you will first
> need to run ./bootstrap in order to generate the build infrastructure.
> This is not necessary for release versions of rdesktop.

**Comment by ashishdoneriya** [comment]
Now I'm getting this error
./bootstrap: 3: ./bootstrap: autoreconf: not found

**Comment by hean01-cendio** [comment]
Ok, you need to install following packages for the build environment:
  - gcc, make, autoconf, automake

**Comment by karugara** [comment]
just run on the prompt -------------   ./nameoftheapp ------------ inside the same folder after extracted and it works!
