### ISSUE TITLE
2 smart cards

### ISSUE THREAD

**Issue by andy-mccarty** [rdesktop/rdesktop#54]
I have Mac osx 10.9 and 10.10.   Compiled rdesktop and runs successfully with 1 smart card attached to machine.  Company just enforced new policy.  Need one token to login to local workstation and a different token to rdp into servers.

If I have both tokens plugged in when I start rdesktop I get the following error   

```
SCARD: SCardGetStatusChange(context: 0x00000001 [0x103fdfa], timeout: 0xffffffff, count: 3)
SCARD:    "\\?PnP?\Notification"
SCARD:        user: 0x0, state: 0x00020001, event: 0x00000000
SCARD:    "SCM SCR 3310 00 00"
SCARD:        user: 0x0, state: 0x00000010, event: 0x00000000
SCARD:    "Aladdin eToken PRO USB 72K Java 01 00"
SCARD:        user: 0x0, state: 0x00000010, event: 0x00000000
SCARD: -> Success
SCARD:    "\\?PnP?\Notification"
SCARD:        user: 0x0, state: 0x00020001, event: 0x00000001
SCARD:    "SCM SCR 3310 00 00"
SCARD:        user: 0x0, state: 0x00000010, event: 0x00000122
SCARD:    "Aladdin eToken PRO USB 72K Java 01 00"
SCARD:        user: 0x0, state: 0x00000010, event: 0x00000122
--> rdpdr_send_completion
rdesktop(18209,0x10dedb000) malloc: *** error for object 0x7f94f041bf50: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

I have some of the prior hexdump if that would be helpful.

For now I will just have to pull out one of the tokens.   But I thought I would report this in case it was something easy to fix.

Thanks
Andy
##

**Comment by uglym8** [comment]
@andy-mccarty, could you reproduce this issue with the current rdesktop?

**Comment by andy-mccarty** [comment]
I am struggling to compile the master branch.  I am on a mac and configure
is failing

"rdesktop requires libXcursor, install the dependency"

So far I have been unsuccessful in getting past this.  If you have any
hints I would be grateful.

**Comment by uglym8** [comment]
Do you have XQuartz installed?
Could please check #162 and verify that you've carefully followed each step.

**Comment by uglym8** [comment]
Closed due to no response
