### ISSUE TITLE
mouse position error correction feature

### ISSUE THREAD

**Issue by shalnoff** [rdesktop/rdesktop#59]
Hi! First of all, thank you for great RDP client! 

It would be great to have command-line option to add horizontal and vertical error correction coefficient for position of mouse pointer. 

I'm using rdesktop for remote control of virtualbox OS which is (for some guest OSs) translating wrong position of mouse with a pretty obvious shift (relatively to the center of the screen in Tablet Mode, which is great for touch screens as well, which makes impractical switching the host mouse pointer off). I spend 2 days to find the way how to fix this issue, unfortunately without any success. This simple feature would be helpful a lot! 
##

**Comment by hean01-cendio** [comment]
We will not add a feature to rdesktop to specify mouse position error offsets. However this might be a bug and more information is needed.

How big is the offset ?
Is this a regression in rdesktop, eg. did it work in earlier versions of rdesktop ?
Can you reproduce the mouse problem with microsoft rdp client ?

**Comment by shalnoff** [comment]
the offset is 0 in the center and increasing closer to borders (i.e. changing relatively to the center of picture). That was tested with the following configuration: 
Linux Mint 17.3 Rosa 64-bit, Kernel Linux 3.19.0-32-generic x86_64, MATE 1.12.0
VirtualBOX Version 5.0.26 r108824

See screenshots. 
![screenshot at 2016-10-17 19 59 34](https://cloud.githubusercontent.com/assets/6167019/19449158/b857da12-94a4-11e6-856c-f83e49c33b7b.png)
![screenshot at 2016-10-17 19 59 40](https://cloud.githubusercontent.com/assets/6167019/19449156/b854121a-94a4-11e6-82bb-2ce34ed1ad11.png)
![screenshot at 2016-10-17 19 59 44](https://cloud.githubusercontent.com/assets/6167019/19449157/b8562a64-94a4-11e6-9aa1-ca011945e761.png)

It could be a problem of coordinates translation of VirtualBOX as well. But I've seen the ticket about practically similar problem in VBox bug tracker, where they asserting that this is the guest OS problem. Eventually I decided to leave ticket and propose this feature here, since this is most obvious workaround -- to have such option for any such coordinates correction issue. The second reason was that after a lot of experiments I found that the VBox + rdesktop is most suitable combination for my needs.

Regarding the MS rdp: unfortunately I have no other host environments to try.

**Comment by shalnoff** [comment]
probably it wouldn't be a problem for mouse usage, but in my case I need to utilize touch screen functionality, which exposing this issue and making impossible guest environment mouse operation.

**Comment by hean01-cendio** [comment]
I just tried to find the bug for VBox and found this [1] which sounds like your problem.

Can your confirm that you have guest additions installed and working ?

[1] https://forums.virtualbox.org/viewtopic.php?f=9&t=4582

**Comment by hean01-cendio** [comment]
Closing due to no response.
