### ISSUE TITLE
disk_query_directory reports incorrect length of non-ASCII file names

### ISSUE THREAD

**Issue by alabuzhev** [rdesktop/rdesktop#60]
Hi guys,

```
https://github.com/rdesktop/rdesktop/blob/master/disk.c

RD_NTSTATUS disk_query_directory(RD_NTHANDLE handle, uint32 info_class, char *pattern, STREAM out)
```

For all `info_class`es there the length of file names reported as: 
`out_uint32_le(out, 2 * strlen(pdirent->d_name) + 2);   /* unicode length */`

Apologies, but this is complete rubbish:
- `pdirent->d_name` is a `char*` pointing to a multibyte UTF-8 string
- it means that any non-ASCII character in that string would be represented by more than one byte, up to four
- you simply can't assume that UTF-16 string length will be `2 * strlen(utf_8_string)`. To get the correct length you need to convert the UTF-8 string to UTF-16 (as you do later in the `rdp_out_unistr`) and report the number of 16-bit characters in that string.

Moreover:
- Length must NOT include the terminating `\0`, so the `+ 2` piece in the quoted line above is also incorrect.

This code seems to be "working" only by coincidence - most of the applications are using `FindFirstFile` API to get directory contents, which copies this data to a fixed size `WIN32_FIND_DATA.cFileName` buffer, so explicit incorrect length is ignored and client calculates it manually, ignoring any trailing zeros.

But all the applications which use `NtQueryDirectoryFile` API (or all the kernel drivers which use `ZwQueryDirectoryFile` API) will receive incorrect length and will not be able to process the file.
##

**Comment by hean01-cendio** [comment]
Hi,

Apology accepted :), there are many things in rdesktop code base that is rubbish and which just works by coincidence. Thanks for spotting and reporting, will prioritize to fix this issue.
