### ISSUE TITLE
rdesktop closes/disconnects while nobody is logged in (solved)

### ISSUE THREAD

**Issue by MAD1695** [rdesktop/rdesktop#63]
I appreciate the opportunity of rdesktop, in comparison to other rdp clients on Linux for the Windows environment which I tried, to be able to connect to the login screen at a usual Windows 10 Pro PC! Choosing the user and typing in it's passwort after the session started offers a great benefit for me! In fact I wasn't able to realize this in any other client. 

But there is a problem where I do not know how to solve it!
After the session is started to the login screen of my PC and no interaction takes place, the session closes on its own after about 20 seconds! While being logged in, there is no such issue. 
I would love to let the session start by an autostart script, but it remains useless if i have to restart the session manually every now and then when the connection closes if I am not ready to type whithin this time.

Thus, I am a noob in Linux, in fact I got my first machine yesterday, i don't know if it's an issue caused by rdesktop or the configuration on the windows pc. But I thought trying to ask the people of the origin of rdesktop would be a nice idea.

I am runnin rdesktop Version 1.8.2 on a Raspberry Pi 3 B latest updates installed

**Comment by hean01-cendio** [comment]
Hi,

> After the session is started to the login screen of my PC and no
> interaction takes place, the session closes on its own after about 20
> seconds! While being logged in, there is no such issue. I would love
> to let the session start by an autostart script, but it remains
> useless if i have to restart the session manually every now and then
> when the connection closes if I am not ready to type whithin this
> time.
> 

This is a behavior in Windows terminal service. I think you can change
this timeout with somehting like [1].

[1]
https://community.spiceworks.com/topic/260587-terminal-server-logon-screen-timout

Kind Regards,

Henrik Andersson

**Comment by MAD1695** [comment]
Thanks very much! Works like a charm now!
For other people with the same issue, this is the solution which worked for me and is given in the Forum where Hendrik Aderssons link is heading to.

> To change the setting you are talking about follow these steps on the server:
>
> 1. Goto: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TerminalServer\WinStations
> \RDP-Tcp
> 2. Create DWORD
> 3. Name: LogonTimeout (DWORD)
> 4. Value: Specifies the time in seconds – Decimal Value – 300. Hex - (12c)its 5 minutes. - 3600. Hex (e10) > is 1hr
> 5. Please reboot the server after adding the above key.
>
> The default is 30 seconds, which is why the window is closing

 I hope it's ok to quote the solution here. I thought it would be helpful to find it here.

Kind regards,

Martin Dreher
