### ISSUE TITLE
Disconnect using RDPv4

### ISSUE THREAD

**Issue by svdb0** [rdesktop/rdesktop#67]
I've found that after upgrading from Ubuntu 14.04 (which uses rdesktop version 1.7.1) to Ubuntu 16.04 (which uses rdesktop version 1.8.3), I can no longer connect to certain hosts.
The console output shows:

> ERROR: channel_register
> WARNING: Initializing sound-support failed!
> ERROR: Connection closed

I have traced the problem to commit 78a4f41f48d91a3938291cafa5c90e3bd78d1aa6.
This adds the following lines to the top of `rdp_out_unistr()`:

> if (string == NULL || len == 0)
>     return;

Before this commit, rdp_out_unistr() would output two null bytes if a zero-length string was passed. At least in some cases, these two bytes seem to be required.

In `rdp_send_logon_info()`, a call `rdp_out_unistr(s, program, len_program)` is made, as part of the construction of an RDPv4 logon packet. If no program was specified, the program field in the logon packet is omitted entirely, causing the remote side to close the connection.

Changing the two lines mentioned above to

> if (string == NULL)
>     return;

fixes the problem, but I am not sure how this affects the bug which commit 78a4f41f48d91a3938291cafa5c90e3bd78d1aa6 intended to solve.

Perhaps such a check would even be better placed in the code which calls `rdp_out_unistr()` instead.
##

**Comment by hean01-cendio** [comment]
> Before this commit, rdp_out_unistr() would output two null bytes if a zero-length string was passed.  At least in some cases, these two bytes seem to be required.

That is very true, and also handled as expected like following code snipped from rdp.c:

```
	int len_program = 2 * strlen(program);
	.
	.
	.
	if (0 < len_program)
		rdp_out_unistr(s, program, len_program);
	else
		out_uint16_le(s, 0);	/* mandatory 2 bytes null terminator */
```

> In rdp_send_logon_info(), a call rdp_out_unistr(s, program, len_program) is made, as part of the construction of an RDPv4 logon packet. If no program was specified, the program field in the logon packet is omitted entirely, causing the remote side to close the connection.

I think your conclusion is wrong here. rdesktop does not omit program field entirely if string is empty as you stated. See above code snippet of how this is handled. This string handling was fixed in 1.8.2 release. (commit 030333d7)

**Comment by hean01-cendio** [comment]
As a round up of your main issue. If the commit 78a4f41 is the reason your connection fails, then somewhere a call to rdp_out_unistr() with empty string is not properly handled. Let me dig around for more information...

**Comment by hean01-cendio** [comment]
Forgive my earlier response. I totally missed that we had specific code for constructing RDP v4 logon packets. I have pushed a fix for this issue.

**Comment by svdb0** [comment]
Thanks. That did fix the problem.

That said, wouldn't it be better for `rdp_out_unistr()` not to have special case behaviour for zero-length strings, so that the calling code would not have to check for this special case and write the zero bytes after all?
(So instead adding a check before calling `rdp_out_unistr()` in the actual special case where a zero-length string means that nothing would need to written, if this case exists at all.)
It seems to me that this would result in cleaner code, and would make bugs like this less likely.

**Comment by hean01-cendio** [comment]
Minor refactoring done in commit 79b9813df553ac
