### ISSUE TITLE
Add better logging capabilities

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#69]
Today different types of logging is a compile time choice. This is very impractical for debugging a problem and we should add debug logging capabilities runtime.
##

**Comment by hean01-cendio** [comment]
A new logging system has been added to rdesktop, no more compile time options to enable debug log.

First off, there was an -v (verbose) command line argument to enable more chatty output for rdesktop. Then debug logging is enabled through an environment variable RDESKTOP_DEBUG as described below.

The following components are currently available and the special name `All` which you will see the use for in the examples belows:

- GUI
- Keyboard
- Clipboard
- Sound
- Protocol
- Graphics
- Core
- SmartCard

Show debug log for all available components:
```
RDESKTOP_DEBUG=All rdesktop <servername>
```

Show debug log for all components except for `Graphics`
```
RDESKTOP_DEBUG=All,!Graphics rdesktop <servername>
```

Show debug log only for component `Graphics`
```
RDESKTOP_DEBUG=Graphics rdesktop <servername>
```

**Comment by wuseman** [comment]
How can I run this now a days? 

I have tried the options above without getting any verbose output at all from commandline, neither does -v works as described. Is there another way to run rdesktop with verbose output now?
