### ISSUE TITLE
Alt-Tab support in Windows/Cygwin version [$15]

### ISSUE THREAD

**Issue by myankele** [rdesktop/rdesktop#7]
Alt-Tab (switching between windows) doesn't work.
1.8.3 version was built on cygwin, running on Windows Vista.

**Comment by Vort** [comment]
You can make Alt+Tab working by changing the start parameters for Cygwin/X.
To do this, open ``cygwin\bin\startxwin`` with text editor and replace ``defaultserverargs="-multiwindow"`` line with ``defaultserverargs="-rootless -keyhook"``.
Then start rdesktop as usually.

I don't know if this is enough for claiming the bounty.

**Comment by Vort** [comment]
Alt+Tab work in "multiwindow" mode was disabled by Cygwin developer with this commit:
http://cgit.freedesktop.org/xorg/xserver/commit/hw/xwin/winkeyhook.c?id=27fc6874b34d70a7ddae5ed8f516f6cfaab518b8
To make this feature work again, you need to revert this patch and rebuild ``XWin.exe`` from ``xorg-server`` package.

**Comment by myankele** [comment]
Ok, I'll give it a try.

**Comment by myankele** [comment]
I spent a few hours trying to build a Cygwin Xwindows.  Eventually I gave up and did as you suggested: single window and -keyhook.  
Thanks a lot.  That's good enough for me, you can take the $, I am not sure how that works though.  I think you need to declare it done.

**Comment by Vort** [comment]
Concerning bounty - I think this issue needs to be closed first.

**Comment by Vort** [comment]
As you are the author of this issue - you can just click "Close issue" button next to "Comment" button.

**Comment by Vort** [comment]
Please accept the claim at
https://www.bountysource.com/issues/26058075-alt-tab-support-in-windows-cygwin-version
Also, I can send you the recompiled version of XWin - just send me an empty e-mail to vvort@yandex.ru

**Comment by myankele** [comment]
I realized after a few days that single window mode is unusable slow in Xwin (no HW graphics acceleration).  So, I did finish rebuilding the Xwin as Vort suggested.  I commented out 
      if (pScreenInfo->fMultiWindow)
          fPassAltTab = FALSE;
And Alt-Tab it works great now in multiwindow mode.
Thanks.
