### ISSUE TITLE
Class 2/3 smart card reader features not working with pcsclite ccid driver

### ISSUE THREAD

**Issue by eheck-is** [rdesktop/rdesktop#75]
The changes in scard.c in commits 1ac2cd1, 91af7ba, b82d367 don't work with class 2 or class 3 smartcard readers that use the ccid driver from the pcsc-lite project. This driver uses control codes that overlap with the 49 << 16 used in Windows codes. In the output of GET_FEATURE_REQUEST these codes are translated to the Windows format. Then when using one of those codes, translation in the other direction is not done because the condition "(dwControlCode & 0xffff0000) == (49 << 16)" always results to false.

This might be fixed be adjusting the mask, but my opinion is that control codes returned by the reader driver should always be left alone, because only this way we can be sure that the driver will understand the codes sent back to it. Translating makes assumptions about the used bits that might not be valid.

**Comment by uglym8** [comment]
@eheck-is, yes, you're absolutely right.
We **must not** modify any feature code from TLV returned by reader for **GET_FEATURE_REQUEST**.
