### ISSUE TITLE
redirect usb com port with rdesktop

### ISSUE THREAD

**Issue by roozgar** [rdesktop/rdesktop#80]
We have several Thin-Clients with debian 8 os and rdesktop in use.

I can use the usb media disk redirect easily like this

`rdesktop -f -u admin -p admin -r disk:usb=/mnt/usb 192.168.1.1`

and it works well.. but i need comport redirection to connect some MICRO and FPGA proggramer to system

rdesktop have aswitch to redirect com port too

`rdesktop -f -u admin -p admin -r comport:com5=/dev/ttyUSB0 192.168.1.1`

but it dont work.

FYI i have access to ttyUSB0 on the this client system..

is there any way to get com port on remote windows?

**Comment by hean01-cendio** [comment]
What version Windows version are you using?

Do you är the COM5 port in the session?

**Comment by roozgar** [comment]
​-i used both 7 and 10 windows
​-yes "lsusb" and "ls /dev/tty*" show my connected devices

but can see port on target windows

**Comment by uglym8** [comment]
@roozgar, just checked usb_to_serial redirection in Win7 and it works just fine.

Are you able to use screen to make sure that you have access to /dev/ttyUSB0 from the local system?
````bash
$ screen /dev/ttyUSB0 115200
````
If it works (if not check permissions for /dev/ttyUSB0 or for **testing only** 
prepend this command with sudo) then run rdesktop with the same options you did before i.e.:

````bash
$ rdesktop -f -u admin -p admin -r comport:com5=/dev/ttyUSB0 192.168.1.1
````
In TS session open either PowerShell or cmd.exe and run "**change port**" cmd
````bash
PS C:\Users\younamehere> change port
COM3 = \Device\Serial0
COM5 = \Device\RdpDrPort\;COM5:2\tsclient\COM5
````
If you see the COM5 line it means that you successfully redirected this port to the TS.
Finally, check that this port is really working:
1) Get **putty** from http://www.putty.org/. 
2) Launch it and set **(1)** Session-> Connection type (Raw, Telnet, Rlogin, SSH, Serial) to **Serial**
**Serial Line:** COM5
**Speed**: 115200 (or any speed your device is requiring for connection)
And hit **Open**.
If you need to change data bits, stop bits etc go to **(2)** and make changes.
![capture_modded](https://user-images.githubusercontent.com/14952529/31016483-8f3d4000-a52d-11e7-8dca-5299df5d6963.PNG)

**Comment by jktz90** [comment]
Is it possible to redirect a USB device  as a COM device? In my case I have a USB smardcard reader which requires communication with the server over COM (drivers on the server simulate a COM port)

**Comment by uglym8** [comment]
Hi!
1) Can you provide the maker and the model of the sc reader?
2) Do I understand correctly that on Windows you see 2 devices; the first one is the virtual COM port
and the second device is reader itself?
I've never seen such readers. Yet:)
I saw USB tokens that manifest themselves as virtual smartcard readers with smartcard always in (e.g. RuToken, eToken).
Usually you have one driver (IFD) which has device dependent part facing the device and PC/SC interface facing PC/SC library and through it to user applications.  

In your case this driver not only does this but also has to provider "usb<-->serial" conversion.
Really strange.

3) Is this reader supported on GNU/Linux? 
Does it require custom driver (provided by manufacturer) or it's CCID-compliant?
If it's supported you can redirect it using **"-r scard"**
But judging by your question I guess it ain't supported.

If your Windows side driver requires usb device then it won't work ATM as we need to add support for RemoteFX to rdesktop.
If on the other hand Windows driver requires serial device AND this reader shows itself as serial device on your GNU/Lnux box then it MAY work.

**Comment by jktz90** [comment]
Hello,
it's a smartcard reader for health insurance cards with a country bound API and its own drivers (WIN/Ubuntu). The reader comes in two version: connected to pc via USB and via r232. The driver creates a virtual COM port for the USB version (in which case you have to install drivers on the local machine). You also have to install the drivers on the server to allow communication between rdp - COM / (and virtual COM port) and the applications.

Im currently using a Raspberry PI 3 with Ubuntu MATE. The r232 version is connected to my PI with a R232/USB converter and the USB version directly. 
The r232 version works perfectly fine with just -r comport:com5=/dev/ttyUSB0 but I have no idea how I am able to send the data from the USB version to the server with a "virtual" COM port.

Here is what freaks me out: I can use the USB version on WTware(also rdp) without any problems while I'm unable to use the R232 version(probably some wrong baudrate). Its the complete opposite compared to rdesktop.

Any ideas?

**Comment by uglym8** [comment]
Are you able to use pure USB (i.e. w/o USB<->RS232 converter) connected reader on Pi3?
Do you have drivers for Ubuntu?
If not, then the only chance at the moment is to use converter as you already did.
Regarding WTware: check this link http://wtware.ru/docs5/remotefx.html (alas it's in Russian only, but title says it all). It seems that they actually use **RemoteFX**.

**Comment by uglym8** [comment]
Sorry, there's actually the English version: http://wtware.com/docs5/remotefx.html

**Comment by jktz90** [comment]
Yes I have drivers installed and I can see the device using libusb. Basically all I need is Ubuntu or rdesktop to simply redirect my USB device to the server as a serial device. Thats why it works with wtware (serial = comx(usb)) and I was wondering if there is any similar command in rdesktop.

**Comment by uglym8** [comment]
Seeing the device via libusb is merely a sign that this device works through USB:)
The main question is: what kind of device your reader + driver is in Ubuntu?

Can you see this device (when connected via USB) as smart card reader in Ubuntu?
Or is it presented as a serial device?

If it's serial device AND you have proper drivers on the Windows side then it MAY work.

Could find your device via 
````bash
$ lsusb
````
and then show verbose info for this device:
````bash
$ lsusb -s Bus:Device -v
````

Check **bInterfaceClass** in **Interface Descriptor**. 
What value does it have?
Or just paste the full command output somewhere and link it here.

**Comment by jktz90** [comment]
Hey,
sorry for not answering but I was struggeling with some other problems and just put the USB reader to the server.


I have another problem tho:
I want to redirect my old serial printer to the server by using a COM to USB adapter since the printer does not work perfectly on ubuntu (printer stops during prints)
![1932_0](https://user-images.githubusercontent.com/29548608/32227747-82dbf8c8-be4c-11e7-9044-76eba0f87d40.jpg)

libusb
Bus 001 Device 004: ID 067b:2305 Prolific Technology, Inc. PL2305 Parallel Port
Bus 001 Device 005: ID 062a:4101 Creative Labs Wireless Keyboard/Mouse
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

hwinfo
Bus 001 Device 004: ID 067b:2305 Prolific Technology, Inc. PL2305 Parallel Port
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x067b Prolific Technology, Inc.
  idProduct          0x2305 PL2305 Parallel Port
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           78
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      1 Unidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       2
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol    255 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval               1



I simply want to redirect this Serial/USB adapter to my server as a COM port with rdesktop -r comport:com5=/dev/.....    .
Thank you

**Comment by uglym8** [comment]
I don't think that it will work as it's a "Prolific Technology, Inc. PL2305 **Parallel** Port".

I reckon that you, at least, should redirect it as **"-r lptport"** though I must admit that I, personally, have never redirected LPT hitherto.

Maybe @hean01-cendio and @derfian could add something up to this discussion.

**Comment by jktz90** [comment]
I found the printer under /dev/usb/lp0. How would you redirect the printer when you dont want to install it directly under linux?

**Comment by uglym8** [comment]
Hello,
sorry for delay in response.

If you can print to this printer in Linux you can redirect it by **"-r printer"**
If you can't or don't want to I guess that ATM it's impossible.

Maybe you can (not in this case though) try to redirect it as **serial** or **lpt**
It could possibly be redirected by using [MS-RDPEUSB](https://msdn.microsoft.com/en-us/library/ff635589/) but it's not yet implemented.

Can you redirect and use it in WTware?

**Comment by uglym8** [comment]
Closed due to no response

**Comment by josefson** [comment]
@uglym8 Nice guide. Would you know how to set the bitrate parameter when passing through this usb to com for the windows session?
