### ISSUE TITLE
Add support for handling High DPI scaling

### ISSUE THREAD

**Issue by nikoneufeld** [rdesktop/rdesktop#81]
Hi,

Sorry if this has been dealt with already. Are there any plans to support high dpi screens on Linux?

**Comment by hean01-cendio** [comment]
Issue #65 and pull request #66 does include some kind of DPI support which might solve this issue.

**Comment by joshudson** [comment]
Indeed; I implemented as much as I could given my system's limitation that the get DPI call returns garbage.

**Comment by uglym8** [comment]
Closing this as #66 has been successfully merged.

**Comment by paulmenzel** [comment]
Could this be easily backported to the 1.8.x branch?

**Comment by CendioOssman** [comment]
We will not be porting any features to 1.8.x, but are rather focusing on getting 1.9.0 out.
