### ISSUE TITLE
Feature request: Add SO_KEEPALIVE option

### ISSUE THREAD

**Issue by rfrht** [rdesktop/rdesktop#84]
Hello there!

I'd like to suggest a switch for enabling SO_KEEPALIVE. Thank you!

**Comment by hean01-cendio** [comment]
This is a server side configuration. See [1] form more details.

[1] https://social.technet.microsoft.com/Forums/windowsserver/en-US/4e86e128-1339-457f-8e37-73c090b95cd5/windows-2008-r2-server-terminal-services-keepalive?forum=winserverTS

**Comment by rfrht** [comment]
Hi Henrik,

Thanks for your consideration.

Of course; The keepalive can be set in the server too. Matter of fact, the keep-alive is configurable on *every* endpoint: Client or server. It is a `socket()` property. If the server does not enables `SO_KEEPALIVE`, the server will honour client-initiated keep-alive packets.

And the reverse is also true: If the server has `SO_KEEPALIVE` enabled but the client is not, the client will correctly reply the server's keepalive replies.

Please allow me add some more evidence so you can reconsider it. The following evidence was taken with a client compiled using the patch.

~~~
[rfreire@rf ~]$ rdesktop 192.168.122.83 &
[rfreire@rf ~]$ netstat -nto | grep 3389
tcp        0      0 192.168.122.1:39806         192.168.122.83:3389         ESTABLISHED off (0.00/0/0)
~~~

As you may see above, the client is not originating any keepalive; it will be completely dependent by Server's keepalive configuration.

Now see the below example:

~~~
[rfreire@rf ~]$ rdesktop 192.168.122.83 &
[rfreire@rf ~]$ netstat -nto | grep 3389
tcp        0      0 192.168.122.1:39818         192.168.122.83:3389         ESTABLISHED keepalive (2.41/0/0)
~~~

Now we have the keepalive enabled and the server will reply the **client's** keepalive settings.

What am I trying to fix here:

During the holidays season I was working using a different ISP, and in this ISP I was behind a [CGNAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT).
The carrier NAT options were pretty aggressive; if the connection were idle for 5 minutes, the NAT entry was dropped at the carrier, and the connection lost to my remote Windows session.

Then, I rebuilt `rdesktop` adding keepalive settings and set some aggressive values, such as: 

~~~
net.ipv4.tcp_keepalive_time=120
net.ipv4.tcp_keepalive_probes=5
net.ipv4.tcp_keepalive_intvl=10
~~~

That means:

Results in the following behavior:

1. Trigger a keepalive probe every 120 seconds if the connection is busy
2. If the connection is idle, probe the remote host every 10 seconds
3. Close the connection after 5 failed probes

By using `rdesktop -J` and that more aggressive client-side keepalive settings, I was able to keep a stable  and persistent network connection.

For what is worth, Windows uses similar default values (check [this link](https://blogs.technet.microsoft.com/nettracer/2010/06/03/things-that-you-may-want-to-know-about-tcp-keepalives/)) as Linux and the [RFC recommendation](https://tools.ietf.org/html/rfc1122#page-101), which is:

1. Trigger a keepalive probe every 7200 seconds (2 hours)
2. If the connection is idle and the remote host does not reply, probe the remote host every 75 seconds
3. Close the connection after 9 failed probes

Which is, unfortunately, not enough for my scenario, due to the large item 1 timeout.

Thus, I kindly ask you to reconsider and merge.

My best regards,

- Rodrigo.
