### ISSUE TITLE
Remove dependency of deprecated libgssglue

### ISSUE THREAD

**Issue by r105m** [rdesktop/rdesktop#92]
Hi, the libgssglue package is required to build your application. But in case of RHEL7 this package is replaced with libtirpc.
```
from rhel 
**Issue**:  package is missing in Red Hat Enterprise Linux 7
**Resolution**:  Red Hat Enterprise Linux 7 the package libgssglue has been replaced by libtirpc. In most cases, the library should no longer be required and libkrb5 can be used.
```
Can you provide building of rdesktop with this package?

**Comment by hean01-cendio** [comment]
The dependency of libgssglue was dropped in PR #131
